// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct EnrollmentMessageSyntax2009PKIResponse {
    pub control_sequence: Vec<EnrollmentMessageSyntax2009TaggedAttribute>,
    pub cms_sequence: Vec<EnrollmentMessageSyntax2009TaggedContentInfo>,
    pub other_msg_sequence: Vec<EnrollmentMessageSyntax2009OtherMsg>,
}

impl EnrollmentMessageSyntax2009PKIResponse {
    pub fn new(control_sequence: Vec<EnrollmentMessageSyntax2009TaggedAttribute>, cms_sequence: Vec<EnrollmentMessageSyntax2009TaggedContentInfo>, other_msg_sequence: Vec<EnrollmentMessageSyntax2009OtherMsg>) -> Self {
        Self {
            control_sequence,
            cms_sequence,
            other_msg_sequence,
        }
    }
}

impl DERParseable for EnrollmentMessageSyntax2009PKIResponse {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let control_sequence: Vec<EnrollmentMessageSyntax2009TaggedAttribute> = { let node = nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?; if let rust_asn1::asn1::Content::Constructed(collection) = node.content { collection.clone().into_iter().map(|child| EnrollmentMessageSyntax2009TaggedAttribute::from_der_node(child)).collect::<Result<_, _>>()? } else { return Err(ASN1Error::new(rust_asn1::errors::ErrorCode::UnexpectedFieldType, "Expected constructed".to_string(), file!().to_string(), line!())); } };
            let cms_sequence: Vec<EnrollmentMessageSyntax2009TaggedContentInfo> = { let node = nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?; if let rust_asn1::asn1::Content::Constructed(collection) = node.content { collection.clone().into_iter().map(|child| EnrollmentMessageSyntax2009TaggedContentInfo::from_der_node(child)).collect::<Result<_, _>>()? } else { return Err(ASN1Error::new(rust_asn1::errors::ErrorCode::UnexpectedFieldType, "Expected constructed".to_string(), file!().to_string(), line!())); } };
            let other_msg_sequence: Vec<EnrollmentMessageSyntax2009OtherMsg> = { let node = nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?; if let rust_asn1::asn1::Content::Constructed(collection) = node.content { collection.clone().into_iter().map(|child| EnrollmentMessageSyntax2009OtherMsg::from_der_node(child)).collect::<Result<_, _>>()? } else { return Err(ASN1Error::new(rust_asn1::errors::ErrorCode::UnexpectedFieldType, "Expected constructed".to_string(), file!().to_string(), line!())); } };
            Ok(Self {
                control_sequence: control_sequence,
                cms_sequence: cms_sequence,
                other_msg_sequence: other_msg_sequence,
            })

        })
    }
}

impl DERSerializable for EnrollmentMessageSyntax2009PKIResponse {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
