// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct EnrollmentMessageSyntax2009IdentityProofV2 {
    pub proof_alg_id: crate::AlgorithmInformation2009Algorithm,
    pub mac_alg_id: crate::AlgorithmInformation2009Algorithm,
    pub witness: ASN1OctetString,
}

impl EnrollmentMessageSyntax2009IdentityProofV2 {
    pub fn new(proof_alg_id: crate::AlgorithmInformation2009Algorithm, mac_alg_id: crate::AlgorithmInformation2009Algorithm, witness: ASN1OctetString) -> Self {
        Self {
            proof_alg_id,
            mac_alg_id,
            witness,
        }
    }
}

impl DERParseable for EnrollmentMessageSyntax2009IdentityProofV2 {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let proof_alg_id = crate::AlgorithmInformation2009Algorithm::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let mac_alg_id = crate::AlgorithmInformation2009Algorithm::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let witness = ASN1OctetString::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                proof_alg_id: proof_alg_id,
                mac_alg_id: mac_alg_id,
                witness: witness,
            })

        })
    }
}

impl DERSerializable for EnrollmentMessageSyntax2009IdentityProofV2 {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
