// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct EnrollmentMessageSyntax2009PendInfo {
    pub pend_token: ASN1OctetString,
    pub pend_time: GeneralizedTime,
}

impl EnrollmentMessageSyntax2009PendInfo {
    pub fn new(pend_token: ASN1OctetString, pend_time: GeneralizedTime) -> Self {
        Self {
            pend_token,
            pend_time,
        }
    }
}

impl DERParseable for EnrollmentMessageSyntax2009PendInfo {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let pend_token = ASN1OctetString::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let pend_time = GeneralizedTime::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                pend_token: pend_token,
                pend_time: pend_time,
            })

        })
    }
}

impl DERSerializable for EnrollmentMessageSyntax2009PendInfo {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
