  // Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum EnrollmentMessageSyntax2009CMCStatus {
    Success = 0,
    Failed = 2,
    Pending = 3,
    NoSupport = 4,
    ConfirmRequired = 5,
    PopRequired = 6,
    Partial = 7,
}

impl DERParseable for EnrollmentMessageSyntax2009CMCStatus {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        let integer = ASN1Integer::from_der_node(node)?;
        // Attempt to convert BigInt to i64
        // ASN1Integer usually wraps BigInt in `value`.
        // We need to import TryInto or use a conversion method.
        // Using `TryInto` requires `use std::convert::TryInto;` in scope or prelude.
        // If `ASN1Integer` doesn't impl `TryInto<i64>`, maybe `integer.value` does.
        // Assuming `integer.value` is BigInt and `num_traits` or similar is available via `rust-asn1`.
        // If not available, we can try formatting to string and parsing (slow but robust fallback?).
        // Or assume `try_into` works on `value`.
        // Error said: `required for ASN1Integer to implement TryInto`. So `integer.try_into()` failed.
        // Let's try `integer.value.try_into()`.
        let val_res: Result<i64, _> = integer.value.try_into();
        let val = val_res.map_err(|_| ASN1Error::new(rust_asn1::errors::ErrorCode::InvalidASN1Object, "Enum value out of range".to_string(), file!().to_string(), line!()))?;
        match val {
            0 => Ok(EnrollmentMessageSyntax2009CMCStatus::Success),
            2 => Ok(EnrollmentMessageSyntax2009CMCStatus::Failed),
            3 => Ok(EnrollmentMessageSyntax2009CMCStatus::Pending),
            4 => Ok(EnrollmentMessageSyntax2009CMCStatus::NoSupport),
            5 => Ok(EnrollmentMessageSyntax2009CMCStatus::ConfirmRequired),
            6 => Ok(EnrollmentMessageSyntax2009CMCStatus::PopRequired),
            7 => Ok(EnrollmentMessageSyntax2009CMCStatus::Partial),
            _ => Err(ASN1Error::new(rust_asn1::errors::ErrorCode::InvalidASN1Object, format!("Unknown value for EnrollmentMessageSyntax2009CMCStatus: {}", val), file!().to_string(), line!()))
        }
    }
}

impl DERSerializable for EnrollmentMessageSyntax2009CMCStatus {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

