// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum IdentifiersAndExpressionsObjectIdExpression {
    CurrentObjectFunction(ASN1Null),
    PrecedingObjectFunction(Box<IdentifiersAndExpressionsObjectIdExpression>),
    SuperiorObjectFunction(Box<IdentifiersAndExpressionsObjectIdExpression>),
    CurrentInstanceFunction(Box<IdentifiersAndExpressionsCurrentInstanceFunction>),
}

impl DERParseable for IdentifiersAndExpressionsObjectIdExpression {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (69, TagClass::ContextSpecific) => Ok(Self::CurrentObjectFunction(ASN1Null::from_der_node(node)?)),
            (70, TagClass::ContextSpecific) => Ok(Self::PrecedingObjectFunction(Box::new(IdentifiersAndExpressionsObjectIdExpression::from_der_node(node)?))),
            (71, TagClass::ContextSpecific) => Ok(Self::SuperiorObjectFunction(Box::new(IdentifiersAndExpressionsObjectIdExpression::from_der_node(node)?))),
            (72, TagClass::ContextSpecific) => Ok(Self::CurrentInstanceFunction(Box::new(IdentifiersAndExpressionsCurrentInstanceFunction::from_der_node(node)?))),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for IdentifiersAndExpressionsObjectIdExpression {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

