// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum IdentifiersAndExpressionsNumericExpression {
    NumericLiteral(ASN1Integer),
    IncrementApplication(Box<IdentifiersAndExpressionsNumericExpression>),
    DecrementApplication(Box<IdentifiersAndExpressionsNumericExpression>),
    OrdinalApplication(crate::IdentifiersAndExpressionsNumericExpressionOrdinalApplicationChoice),
    BindingReference(crate::IdentifiersAndExpressionsBindingReference),
}

impl DERParseable for IdentifiersAndExpressionsNumericExpression {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (76, TagClass::ContextSpecific) => Ok(Self::NumericLiteral(ASN1Integer::from_der_node(node)?)),
            (77, TagClass::ContextSpecific) => Ok(Self::IncrementApplication(Box::new(IdentifiersAndExpressionsNumericExpression::from_der_node(node)?))),
            (78, TagClass::ContextSpecific) => Ok(Self::DecrementApplication(Box::new(IdentifiersAndExpressionsNumericExpression::from_der_node(node)?))),
            (79, TagClass::ContextSpecific) => Ok(Self::OrdinalApplication(crate::IdentifiersAndExpressionsNumericExpressionOrdinalApplicationChoice::from_der_node(node)?)),
            (82, TagClass::ContextSpecific) => Ok(Self::BindingReference(crate::IdentifiersAndExpressionsBindingReference::from_der_node(node)?)),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for IdentifiersAndExpressionsNumericExpression {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

