// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIX1Implicit2009UserNotice {
    pub notice_ref: Option<PKIX1Implicit2009NoticeReference>,
    pub explicit_text: Option<PKIX1Implicit2009DisplayText>,
}

impl PKIX1Implicit2009UserNotice {
    pub fn new(notice_ref: Option<PKIX1Implicit2009NoticeReference>, explicit_text: Option<PKIX1Implicit2009DisplayText>) -> Self {
        Self {
            notice_ref,
            explicit_text,
        }
    }
}

impl DERParseable for PKIX1Implicit2009UserNotice {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let notice_ref: Option<PKIX1Implicit2009NoticeReference> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match PKIX1Implicit2009NoticeReference::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let explicit_text: Option<PKIX1Implicit2009DisplayText> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match PKIX1Implicit2009DisplayText::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                notice_ref: notice_ref,
                explicit_text: explicit_text,
            })

        })
    }
}

impl DERSerializable for PKIX1Implicit2009UserNotice {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
