// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct SMIMESymmetricKeyDistribution2009GLInfo {
    pub gl_name: crate::PKIX1Implicit2009GeneralName,
    pub gl_address: crate::PKIX1Implicit2009GeneralName,
}

impl SMIMESymmetricKeyDistribution2009GLInfo {
    pub fn new(gl_name: crate::PKIX1Implicit2009GeneralName, gl_address: crate::PKIX1Implicit2009GeneralName) -> Self {
        Self {
            gl_name,
            gl_address,
        }
    }
}

impl DERParseable for SMIMESymmetricKeyDistribution2009GLInfo {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let gl_name = crate::PKIX1Implicit2009GeneralName::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let gl_address = crate::PKIX1Implicit2009GeneralName::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                gl_name: gl_name,
                gl_address: gl_address,
            })

        })
    }
}

impl DERSerializable for SMIMESymmetricKeyDistribution2009GLInfo {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
