  // Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum ANSIX942SchemeNumber {
    DhStaticSha1 = 0,
    DhEphemSha1 = 1,
    DhOneFlowSha1 = 2,
    DhHybrid1Sha1 = 3,
    DhHybrid2Sha1 = 4,
    DhHybridOneFlowSha1 = 5,
    Mqv2Sha1 = 6,
    Mqv1Sha1 = 7,

}

impl DERParseable for ANSIX942SchemeNumber {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        let integer = ASN1Integer::from_der_node(node)?;
        // Attempt to convert BigInt to i64
        // ASN1Integer usually wraps BigInt in `value`.
        // We need to import TryInto or use a conversion method.
        // Using `TryInto` requires `use std::convert::TryInto;` in scope or prelude.
        // If `ASN1Integer` doesn't impl `TryInto<i64>`, maybe `integer.value` does.
        // Assuming `integer.value` is BigInt and `num_traits` or similar is available via `rust-asn1`.
        // If not available, we can try formatting to string and parsing (slow but robust fallback?).
        // Or assume `try_into` works on `value`.
        // Error said: `required for ASN1Integer to implement TryInto`. So `integer.try_into()` failed.
        // Let's try `integer.value.try_into()`.
        let val_res: Result<i64, _> = integer.value.try_into();
        let val = val_res.map_err(|_| ASN1Error::new(rust_asn1::errors::ErrorCode::InvalidASN1Object, "Enum value out of range".to_string(), file!().to_string(), line!()))?;
        match val {
            0 => Ok(ANSIX942SchemeNumber::DhStaticSha1),
            1 => Ok(ANSIX942SchemeNumber::DhEphemSha1),
            2 => Ok(ANSIX942SchemeNumber::DhOneFlowSha1),
            3 => Ok(ANSIX942SchemeNumber::DhHybrid1Sha1),
            4 => Ok(ANSIX942SchemeNumber::DhHybrid2Sha1),
            5 => Ok(ANSIX942SchemeNumber::DhHybridOneFlowSha1),
            6 => Ok(ANSIX942SchemeNumber::Mqv2Sha1),
            7 => Ok(ANSIX942SchemeNumber::Mqv1Sha1),

            _ => Err(ASN1Error::new(rust_asn1::errors::ErrorCode::InvalidASN1Object, format!("Unknown value for ANSIX942SchemeNumber: {}", val), file!().to_string(), line!()))
        }
    }
}

impl DERSerializable for ANSIX942SchemeNumber {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

