// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct AuthenticationFrameworkHASH {
    pub algorithm_identifier: crate::AuthenticationFrameworkAlgorithmIdentifier,
    pub hash_value: ASN1BitString,
}

impl AuthenticationFrameworkHASH {
    pub fn new(algorithm_identifier: crate::AuthenticationFrameworkAlgorithmIdentifier, hash_value: ASN1BitString) -> Self {
        Self {
            algorithm_identifier,
            hash_value,
        }
    }
}

impl DERParseable for AuthenticationFrameworkHASH {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let algorithm_identifier = crate::AuthenticationFrameworkAlgorithmIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let hash_value = ASN1BitString::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                algorithm_identifier: algorithm_identifier,
                hash_value: hash_value,
            })

        })
    }
}

impl DERSerializable for AuthenticationFrameworkHASH {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
