// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct AuthenticationFrameworkAttributeCertificationPath {
    pub attribute_certificate: crate::AuthenticationFrameworkAttributeCertificate,
    pub ac_path: Option<Vec<AuthenticationFrameworkACPathData>>,
}

impl AuthenticationFrameworkAttributeCertificationPath {
    pub fn new(attribute_certificate: crate::AuthenticationFrameworkAttributeCertificate, ac_path: Option<Vec<AuthenticationFrameworkACPathData>>) -> Self {
        Self {
            attribute_certificate,
            ac_path,
        }
    }
}

impl DERParseable for AuthenticationFrameworkAttributeCertificationPath {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let attribute_certificate = crate::AuthenticationFrameworkAttributeCertificate::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let ac_path: Option<Vec<AuthenticationFrameworkACPathData>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| AuthenticationFrameworkACPathData::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            Ok(Self {
                attribute_certificate: attribute_certificate,
                ac_path: ac_path,
            })

        })
    }
}

impl DERSerializable for AuthenticationFrameworkAttributeCertificationPath {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
