// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct BasicAccessControlACIItem {
    pub identification_tag: crate::SelectedAttributeTypesDirectoryString,
    pub precedence: crate::BasicAccessControlPrecedence,
    pub authentication_level: crate::BasicAccessControlAuthenticationLevel,
    pub item_or_user_first: crate::BasicAccessControlACIItemItemOrUserFirstChoice,
}

impl BasicAccessControlACIItem {
    pub fn new(identification_tag: crate::SelectedAttributeTypesDirectoryString, precedence: crate::BasicAccessControlPrecedence, authentication_level: crate::BasicAccessControlAuthenticationLevel, item_or_user_first: crate::BasicAccessControlACIItemItemOrUserFirstChoice) -> Self {
        Self {
            identification_tag,
            precedence,
            authentication_level,
            item_or_user_first,
        }
    }
}

impl DERParseable for BasicAccessControlACIItem {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let identification_tag = crate::SelectedAttributeTypesDirectoryString::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let precedence = crate::BasicAccessControlPrecedence::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let authentication_level = crate::BasicAccessControlAuthenticationLevel::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let item_or_user_first = crate::BasicAccessControlACIItemItemOrUserFirstChoice::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                identification_tag: identification_tag,
                precedence: precedence,
                authentication_level: authentication_level,
                item_or_user_first: item_or_user_first,
            })

        })
    }
}

impl DERSerializable for BasicAccessControlACIItem {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
