// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct BasicAccessControlACIItemItemOrUserFirstChoiceUserFirstSequence {
    pub user_classes: crate::BasicAccessControlUserClasses,
    pub user_permissions: Vec<BasicAccessControlUserPermission>,
}

impl BasicAccessControlACIItemItemOrUserFirstChoiceUserFirstSequence {
    pub fn new(user_classes: crate::BasicAccessControlUserClasses, user_permissions: Vec<BasicAccessControlUserPermission>) -> Self {
        Self {
            user_classes,
            user_permissions,
        }
    }
}

impl DERParseable for BasicAccessControlACIItemItemOrUserFirstChoiceUserFirstSequence {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let user_classes = crate::BasicAccessControlUserClasses::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let user_permissions: Vec<BasicAccessControlUserPermission> = { let node = nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?; if let rust_asn1::asn1::Content::Constructed(collection) = node.content { collection.clone().into_iter().map(|child| BasicAccessControlUserPermission::from_der_node(child)).collect::<Result<_, _>>()? } else { return Err(ASN1Error::new(rust_asn1::errors::ErrorCode::UnexpectedFieldType, "Expected constructed".to_string(), file!().to_string(), line!())); } };
            Ok(Self {
                user_classes: user_classes,
                user_permissions: user_permissions,
            })

        })
    }
}

impl DERSerializable for BasicAccessControlACIItemItemOrUserFirstChoiceUserFirstSequence {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
