// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct BasicAccessControlProtectedItems {
    pub entry: Option<ASN1Null>,
    pub all_user_attribute_types: Option<ASN1Null>,
    pub attribute_type: Option<Vec<ASN1ObjectIdentifier>>,
    pub all_attribute_values: Option<Vec<ASN1ObjectIdentifier>>,
    pub all_user_attribute_types_and_values: Option<ASN1Null>,
    pub attribute_value: Option<Vec<BasicAccessControlAttributeTypeAndValue>>,
    pub self_value: Option<Vec<ASN1ObjectIdentifier>>,
    pub range_of_values: Option<crate::DirectoryAbstractServiceFilter>,
    pub max_value_count: Option<Vec<BasicAccessControlMaxValueCount>>,
    pub max_imm_sub: Option<ASN1Integer>,
    pub restricted_by: Option<Vec<BasicAccessControlRestrictedValue>>,
    pub contexts: Option<Vec<InformationFrameworkContextAssertion>>,
    pub classes: Option<crate::InformationFrameworkRefinement>,
}

impl BasicAccessControlProtectedItems {
    pub fn new(entry: Option<ASN1Null>, all_user_attribute_types: Option<ASN1Null>, attribute_type: Option<Vec<ASN1ObjectIdentifier>>, all_attribute_values: Option<Vec<ASN1ObjectIdentifier>>, all_user_attribute_types_and_values: Option<ASN1Null>, attribute_value: Option<Vec<BasicAccessControlAttributeTypeAndValue>>, self_value: Option<Vec<ASN1ObjectIdentifier>>, range_of_values: Option<crate::DirectoryAbstractServiceFilter>, max_value_count: Option<Vec<BasicAccessControlMaxValueCount>>, max_imm_sub: Option<ASN1Integer>, restricted_by: Option<Vec<BasicAccessControlRestrictedValue>>, contexts: Option<Vec<InformationFrameworkContextAssertion>>, classes: Option<crate::InformationFrameworkRefinement>) -> Self {
        Self {
            entry,
            all_user_attribute_types,
            attribute_type,
            all_attribute_values,
            all_user_attribute_types_and_values,
            attribute_value,
            self_value,
            range_of_values,
            max_value_count,
            max_imm_sub,
            restricted_by,
            contexts,
            classes,
        }
    }
}

impl DERParseable for BasicAccessControlProtectedItems {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let entry: Option<ASN1Null> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1Null::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let all_user_attribute_types: Option<ASN1Null> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1Null::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let attribute_type: Option<Vec<ASN1ObjectIdentifier>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ASN1ObjectIdentifier::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let all_attribute_values: Option<Vec<ASN1ObjectIdentifier>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ASN1ObjectIdentifier::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let all_user_attribute_types_and_values: Option<ASN1Null> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1Null::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let attribute_value: Option<Vec<BasicAccessControlAttributeTypeAndValue>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| BasicAccessControlAttributeTypeAndValue::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let self_value: Option<Vec<ASN1ObjectIdentifier>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ASN1ObjectIdentifier::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let range_of_values: Option<crate::DirectoryAbstractServiceFilter> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DirectoryAbstractServiceFilter::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let max_value_count: Option<Vec<BasicAccessControlMaxValueCount>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| BasicAccessControlMaxValueCount::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let max_imm_sub: Option<ASN1Integer> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1Integer::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let restricted_by: Option<Vec<BasicAccessControlRestrictedValue>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| BasicAccessControlRestrictedValue::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let contexts: Option<Vec<InformationFrameworkContextAssertion>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| InformationFrameworkContextAssertion::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let classes: Option<crate::InformationFrameworkRefinement> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::InformationFrameworkRefinement::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                entry: entry,
                all_user_attribute_types: all_user_attribute_types,
                attribute_type: attribute_type,
                all_attribute_values: all_attribute_values,
                all_user_attribute_types_and_values: all_user_attribute_types_and_values,
                attribute_value: attribute_value,
                self_value: self_value,
                range_of_values: range_of_values,
                max_value_count: max_value_count,
                max_imm_sub: max_imm_sub,
                restricted_by: restricted_by,
                contexts: contexts,
                classes: classes,
            })

        })
    }
}

impl DERSerializable for BasicAccessControlProtectedItems {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
