// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct BasicAccessControlItemPermission {
    pub precedence: Option<crate::BasicAccessControlPrecedence>,
    pub user_classes: crate::BasicAccessControlUserClasses,
    pub grants_and_denials: crate::BasicAccessControlGrantsAndDenials,
}

impl BasicAccessControlItemPermission {
    pub fn new(precedence: Option<crate::BasicAccessControlPrecedence>, user_classes: crate::BasicAccessControlUserClasses, grants_and_denials: crate::BasicAccessControlGrantsAndDenials) -> Self {
        Self {
            precedence,
            user_classes,
            grants_and_denials,
        }
    }
}

impl DERParseable for BasicAccessControlItemPermission {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let precedence: Option<crate::BasicAccessControlPrecedence> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::BasicAccessControlPrecedence::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let user_classes = crate::BasicAccessControlUserClasses::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let grants_and_denials = crate::BasicAccessControlGrantsAndDenials::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                precedence: precedence,
                user_classes: user_classes,
                grants_and_denials: grants_and_denials,
            })

        })
    }
}

impl DERSerializable for BasicAccessControlItemPermission {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
