// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct ColourAttributesCMYKCalibration {
    pub referencewhite: crate::ColourAttributesCIERef,
    pub comment: Option<crate::DocumentProfileDescriptorCharacterData>,
    pub cmyklut: crate::ColourAttributesGridSpecification,
}

impl ColourAttributesCMYKCalibration {
    pub fn new(referencewhite: crate::ColourAttributesCIERef, comment: Option<crate::DocumentProfileDescriptorCharacterData>, cmyklut: crate::ColourAttributesGridSpecification) -> Self {
        Self {
            referencewhite,
            comment,
            cmyklut,
        }
    }
}

impl DERParseable for ColourAttributesCMYKCalibration {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let referencewhite = crate::ColourAttributesCIERef::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let comment: Option<crate::DocumentProfileDescriptorCharacterData> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorCharacterData::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let cmyklut = crate::ColourAttributesGridSpecification::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                referencewhite: referencewhite,
                comment: comment,
                cmyklut: cmyklut,
            })

        })
    }
}

impl DERSerializable for ColourAttributesCMYKCalibration {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
