// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct CryptographicMessageSyntax2010AuthenticatedData {
    pub version: crate::CryptographicMessageSyntax2010CMSVersion,
    pub originator_info: Option<crate::CryptographicMessageSyntax2010OriginatorInfo>,
    pub recipient_infos: crate::CryptographicMessageSyntax2010RecipientInfos,
    pub mac_algorithm: crate::CryptographicMessageSyntax2010MessageAuthenticationCodeAlgorithm,
    pub digest_algorithm: Option<crate::CryptographicMessageSyntax2010DigestAlgorithmIdentifier>,
    pub encap_content_info: crate::CryptographicMessageSyntax2010EncapsulatedContentInfo,
    pub auth_attrs: Option<crate::CryptographicMessageSyntax2010AuthAttributes>,
    pub mac: crate::CryptographicMessageSyntax2010MessageAuthenticationCode,
    pub unauth_attrs: Option<crate::CryptographicMessageSyntax2010UnauthAttributes>,
}

impl CryptographicMessageSyntax2010AuthenticatedData {
    pub fn new(version: crate::CryptographicMessageSyntax2010CMSVersion, originator_info: Option<crate::CryptographicMessageSyntax2010OriginatorInfo>, recipient_infos: crate::CryptographicMessageSyntax2010RecipientInfos, mac_algorithm: crate::CryptographicMessageSyntax2010MessageAuthenticationCodeAlgorithm, digest_algorithm: Option<crate::CryptographicMessageSyntax2010DigestAlgorithmIdentifier>, encap_content_info: crate::CryptographicMessageSyntax2010EncapsulatedContentInfo, auth_attrs: Option<crate::CryptographicMessageSyntax2010AuthAttributes>, mac: crate::CryptographicMessageSyntax2010MessageAuthenticationCode, unauth_attrs: Option<crate::CryptographicMessageSyntax2010UnauthAttributes>) -> Self {
        Self {
            version,
            originator_info,
            recipient_infos,
            mac_algorithm,
            digest_algorithm,
            encap_content_info,
            auth_attrs,
            mac,
            unauth_attrs,
        }
    }
}

impl DERParseable for CryptographicMessageSyntax2010AuthenticatedData {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let version = crate::CryptographicMessageSyntax2010CMSVersion::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let originator_info: Option<crate::CryptographicMessageSyntax2010OriginatorInfo> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::CryptographicMessageSyntax2010OriginatorInfo::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let recipient_infos = crate::CryptographicMessageSyntax2010RecipientInfos::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let mac_algorithm = crate::CryptographicMessageSyntax2010MessageAuthenticationCodeAlgorithm::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let digest_algorithm: Option<crate::CryptographicMessageSyntax2010DigestAlgorithmIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::CryptographicMessageSyntax2010DigestAlgorithmIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let encap_content_info = crate::CryptographicMessageSyntax2010EncapsulatedContentInfo::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let auth_attrs: Option<crate::CryptographicMessageSyntax2010AuthAttributes> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::CryptographicMessageSyntax2010AuthAttributes::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let mac = crate::CryptographicMessageSyntax2010MessageAuthenticationCode::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let unauth_attrs: Option<crate::CryptographicMessageSyntax2010UnauthAttributes> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::CryptographicMessageSyntax2010UnauthAttributes::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                version: version,
                originator_info: originator_info,
                recipient_infos: recipient_infos,
                mac_algorithm: mac_algorithm,
                digest_algorithm: digest_algorithm,
                encap_content_info: encap_content_info,
                auth_attrs: auth_attrs,
                mac: mac,
                unauth_attrs: unauth_attrs,
            })

        })
    }
}

impl DERSerializable for CryptographicMessageSyntax2010AuthenticatedData {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
