// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct CryptographicMessageSyntax2009SignedData {
    pub version: crate::CryptographicMessageSyntax2009CMSVersion,
    pub digest_algorithms: Vec<CryptographicMessageSyntax2009DigestAlgorithmIdentifier>,
    pub encap_content_info: crate::CryptographicMessageSyntax2009EncapsulatedContentInfo,
    pub certificates: Option<crate::CryptographicMessageSyntax2009CertificateSet>,
    pub crls: Option<crate::CryptographicMessageSyntax2009RevocationInfoChoices>,
    pub signer_infos: crate::CryptographicMessageSyntax2009SignerInfos,
}

impl CryptographicMessageSyntax2009SignedData {
    pub fn new(version: crate::CryptographicMessageSyntax2009CMSVersion, digest_algorithms: Vec<CryptographicMessageSyntax2009DigestAlgorithmIdentifier>, encap_content_info: crate::CryptographicMessageSyntax2009EncapsulatedContentInfo, certificates: Option<crate::CryptographicMessageSyntax2009CertificateSet>, crls: Option<crate::CryptographicMessageSyntax2009RevocationInfoChoices>, signer_infos: crate::CryptographicMessageSyntax2009SignerInfos) -> Self {
        Self {
            version,
            digest_algorithms,
            encap_content_info,
            certificates,
            crls,
            signer_infos,
        }
    }
}

impl DERParseable for CryptographicMessageSyntax2009SignedData {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let version = crate::CryptographicMessageSyntax2009CMSVersion::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let digest_algorithms: Vec<CryptographicMessageSyntax2009DigestAlgorithmIdentifier> = { let node = nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?; if let rust_asn1::asn1::Content::Constructed(collection) = node.content { collection.clone().into_iter().map(|child| CryptographicMessageSyntax2009DigestAlgorithmIdentifier::from_der_node(child)).collect::<Result<_, _>>()? } else { return Err(ASN1Error::new(rust_asn1::errors::ErrorCode::UnexpectedFieldType, "Expected constructed".to_string(), file!().to_string(), line!())); } };
            let encap_content_info = crate::CryptographicMessageSyntax2009EncapsulatedContentInfo::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let certificates: Option<crate::CryptographicMessageSyntax2009CertificateSet> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::CryptographicMessageSyntax2009CertificateSet::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let crls: Option<crate::CryptographicMessageSyntax2009RevocationInfoChoices> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::CryptographicMessageSyntax2009RevocationInfoChoices::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let signer_infos = crate::CryptographicMessageSyntax2009SignerInfos::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                version: version,
                digest_algorithms: digest_algorithms,
                encap_content_info: encap_content_info,
                certificates: certificates,
                crls: crls,
                signer_infos: signer_infos,
            })

        })
    }
}

impl DERSerializable for CryptographicMessageSyntax2009SignedData {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
