// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum DirectoryAbstractServiceFilter {
    Item(crate::DirectoryAbstractServiceFilterItem),
    And(Vec<DirectoryAbstractServiceFilter>),
    Or(Vec<DirectoryAbstractServiceFilter>),
    Not(Box<DirectoryAbstractServiceFilter>),
}

impl DERParseable for DirectoryAbstractServiceFilter {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (153, TagClass::ContextSpecific) => Ok(Self::Item(crate::DirectoryAbstractServiceFilterItem::from_der_node(node)?)),
            (154, TagClass::ContextSpecific) => Ok(Self::And(rust_asn1::der::sequence_of(rust_asn1::asn1_types::ASN1Identifier::SEQUENCE, node)?)),
            (155, TagClass::ContextSpecific) => Ok(Self::Or(rust_asn1::der::sequence_of(rust_asn1::asn1_types::ASN1Identifier::SEQUENCE, node)?)),
            (156, TagClass::ContextSpecific) => Ok(Self::Not(Box::new(DirectoryAbstractServiceFilter::from_der_node(node)?))),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for DirectoryAbstractServiceFilter {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

