// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct DocumentProfileDescriptorProtectedDocPartsElement {
    pub protecteddocpartid: crate::IdentifiersAndExpressionsProtectedPartIdentifier,
    pub privrecipientsinfo: Vec<DocumentProfileDescriptorPrivRecipientsInfo>,
}

impl DocumentProfileDescriptorProtectedDocPartsElement {
    pub fn new(protecteddocpartid: crate::IdentifiersAndExpressionsProtectedPartIdentifier, privrecipientsinfo: Vec<DocumentProfileDescriptorPrivRecipientsInfo>) -> Self {
        Self {
            protecteddocpartid,
            privrecipientsinfo,
        }
    }
}

impl DERParseable for DocumentProfileDescriptorProtectedDocPartsElement {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let protecteddocpartid = crate::IdentifiersAndExpressionsProtectedPartIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let privrecipientsinfo: Vec<DocumentProfileDescriptorPrivRecipientsInfo> = { let node = nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?; if let rust_asn1::asn1::Content::Constructed(collection) = node.content { collection.clone().into_iter().map(|child| DocumentProfileDescriptorPrivRecipientsInfo::from_der_node(child)).collect::<Result<_, _>>()? } else { return Err(ASN1Error::new(rust_asn1::errors::ErrorCode::UnexpectedFieldType, "Expected constructed".to_string(), file!().to_string(), line!())); } };
            Ok(Self {
                protecteddocpartid: protecteddocpartid,
                privrecipientsinfo: privrecipientsinfo,
            })

        })
    }
}

impl DERSerializable for DocumentProfileDescriptorProtectedDocPartsElement {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
