// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct DocumentProfileDescriptorDocumentSecurityAttributes {
    pub sealedinfoencoding: Option<ASN1ObjectIdentifier>,
    pub odasecuritylabel: Option<crate::DocumentProfileDescriptorOdaSecurityLabel>,
    pub sealeddocprofiles: Option<crate::DocumentProfileDescriptorSealedDocProfiles>,
    pub presealeddocbodyparts: Option<crate::DocumentProfileDescriptorSealedDocBodyparts>,
    pub postsealeddocbodyparts: Option<crate::DocumentProfileDescriptorSealedDocBodyparts>,
    pub enciphereddocprofiles: Option<crate::DocumentProfileDescriptorProtectedDocParts>,
    pub preenciphereddocbodyparts: Option<crate::DocumentProfileDescriptorProtectedDocParts>,
    pub postenciphereddocbodyparts: Option<crate::DocumentProfileDescriptorProtectedDocParts>,
    pub sealedlinks: Option<crate::DocumentProfileDescriptorSealedDocBodyparts>,
}

impl DocumentProfileDescriptorDocumentSecurityAttributes {
    pub fn new(sealedinfoencoding: Option<ASN1ObjectIdentifier>, odasecuritylabel: Option<crate::DocumentProfileDescriptorOdaSecurityLabel>, sealeddocprofiles: Option<crate::DocumentProfileDescriptorSealedDocProfiles>, presealeddocbodyparts: Option<crate::DocumentProfileDescriptorSealedDocBodyparts>, postsealeddocbodyparts: Option<crate::DocumentProfileDescriptorSealedDocBodyparts>, enciphereddocprofiles: Option<crate::DocumentProfileDescriptorProtectedDocParts>, preenciphereddocbodyparts: Option<crate::DocumentProfileDescriptorProtectedDocParts>, postenciphereddocbodyparts: Option<crate::DocumentProfileDescriptorProtectedDocParts>, sealedlinks: Option<crate::DocumentProfileDescriptorSealedDocBodyparts>) -> Self {
        Self {
            sealedinfoencoding,
            odasecuritylabel,
            sealeddocprofiles,
            presealeddocbodyparts,
            postsealeddocbodyparts,
            enciphereddocprofiles,
            preenciphereddocbodyparts,
            postenciphereddocbodyparts,
            sealedlinks,
        }
    }
}

impl DERParseable for DocumentProfileDescriptorDocumentSecurityAttributes {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let sealedinfoencoding: Option<ASN1ObjectIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1ObjectIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let odasecuritylabel: Option<crate::DocumentProfileDescriptorOdaSecurityLabel> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorOdaSecurityLabel::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let sealeddocprofiles: Option<crate::DocumentProfileDescriptorSealedDocProfiles> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorSealedDocProfiles::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let presealeddocbodyparts: Option<crate::DocumentProfileDescriptorSealedDocBodyparts> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorSealedDocBodyparts::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let postsealeddocbodyparts: Option<crate::DocumentProfileDescriptorSealedDocBodyparts> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorSealedDocBodyparts::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let enciphereddocprofiles: Option<crate::DocumentProfileDescriptorProtectedDocParts> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorProtectedDocParts::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let preenciphereddocbodyparts: Option<crate::DocumentProfileDescriptorProtectedDocParts> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorProtectedDocParts::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let postenciphereddocbodyparts: Option<crate::DocumentProfileDescriptorProtectedDocParts> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorProtectedDocParts::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let sealedlinks: Option<crate::DocumentProfileDescriptorSealedDocBodyparts> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorSealedDocBodyparts::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                sealedinfoencoding: sealedinfoencoding,
                odasecuritylabel: odasecuritylabel,
                sealeddocprofiles: sealeddocprofiles,
                presealeddocbodyparts: presealeddocbodyparts,
                postsealeddocbodyparts: postsealeddocbodyparts,
                enciphereddocprofiles: enciphereddocprofiles,
                preenciphereddocbodyparts: preenciphereddocbodyparts,
                postenciphereddocbodyparts: postenciphereddocbodyparts,
                sealedlinks: sealedlinks,
            })

        })
    }
}

impl DERSerializable for DocumentProfileDescriptorDocumentSecurityAttributes {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
