// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct DocumentProfileDescriptorAdditionalDocCharacteristics {
    pub unitscaling: Option<crate::DocumentProfileDescriptorAdditionalDocCharacteristicsUnitScalingSequence>,
    pub fontslist: Option<crate::DocumentProfileDescriptorFontsList>,
    pub colourcharacteristics: Option<crate::ColourAttributesColourCharacteristics>,
    pub colourspaceslist: Option<crate::ColourAttributesColourSpacesList>,
    pub assuredreproductionareas: Option<crate::DocumentProfileDescriptorAssuredReproductionAreas>,
    pub timescaling: Option<crate::TemporalRelationshipsTimeScaling>,
    pub documentpresentationtime: Option<crate::TemporalRelationshipsDocumentPresentationTime>,
}

impl DocumentProfileDescriptorAdditionalDocCharacteristics {
    pub fn new(unitscaling: Option<crate::DocumentProfileDescriptorAdditionalDocCharacteristicsUnitScalingSequence>, fontslist: Option<crate::DocumentProfileDescriptorFontsList>, colourcharacteristics: Option<crate::ColourAttributesColourCharacteristics>, colourspaceslist: Option<crate::ColourAttributesColourSpacesList>, assuredreproductionareas: Option<crate::DocumentProfileDescriptorAssuredReproductionAreas>, timescaling: Option<crate::TemporalRelationshipsTimeScaling>, documentpresentationtime: Option<crate::TemporalRelationshipsDocumentPresentationTime>) -> Self {
        Self {
            unitscaling,
            fontslist,
            colourcharacteristics,
            colourspaceslist,
            assuredreproductionareas,
            timescaling,
            documentpresentationtime,
        }
    }
}

impl DERParseable for DocumentProfileDescriptorAdditionalDocCharacteristics {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let unitscaling: Option<crate::DocumentProfileDescriptorAdditionalDocCharacteristicsUnitScalingSequence> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorAdditionalDocCharacteristicsUnitScalingSequence::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let fontslist: Option<crate::DocumentProfileDescriptorFontsList> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorFontsList::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let colourcharacteristics: Option<crate::ColourAttributesColourCharacteristics> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::ColourAttributesColourCharacteristics::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let colourspaceslist: Option<crate::ColourAttributesColourSpacesList> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::ColourAttributesColourSpacesList::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let assuredreproductionareas: Option<crate::DocumentProfileDescriptorAssuredReproductionAreas> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorAssuredReproductionAreas::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let timescaling: Option<crate::TemporalRelationshipsTimeScaling> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::TemporalRelationshipsTimeScaling::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let documentpresentationtime: Option<crate::TemporalRelationshipsDocumentPresentationTime> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::TemporalRelationshipsDocumentPresentationTime::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                unitscaling: unitscaling,
                fontslist: fontslist,
                colourcharacteristics: colourcharacteristics,
                colourspaceslist: colourspaceslist,
                assuredreproductionareas: assuredreproductionareas,
                timescaling: timescaling,
                documentpresentationtime: documentpresentationtime,
            })

        })
    }
}

impl DERSerializable for DocumentProfileDescriptorAdditionalDocCharacteristics {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
