// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum DSTU4145ParamsDefinitionChoice {
    Ecbinary(crate::DSTUECBinary),
    NamedCurve(ASN1ObjectIdentifier),
}

impl DERParseable for DSTU4145ParamsDefinitionChoice {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (0, TagClass::ContextSpecific) => Ok(Self::Ecbinary(crate::DSTUECBinary::from_der_node(node)?)),
            (1, TagClass::ContextSpecific) => Ok(Self::NamedCurve(ASN1ObjectIdentifier::from_der_node(node)?)),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for DSTU4145ParamsDefinitionChoice {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

