// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct EnrollmentMessageSyntax2009ModCertTemplate {
    pub pki_data_reference: crate::EnrollmentMessageSyntax2009BodyPartPath,
    pub cert_references: crate::EnrollmentMessageSyntax2009BodyPartList,
    pub replace: ASN1Boolean,
    pub cert_template: crate::PKIXCRMF2009CertTemplate,
}

impl EnrollmentMessageSyntax2009ModCertTemplate {
    pub fn new(pki_data_reference: crate::EnrollmentMessageSyntax2009BodyPartPath, cert_references: crate::EnrollmentMessageSyntax2009BodyPartList, replace: ASN1Boolean, cert_template: crate::PKIXCRMF2009CertTemplate) -> Self {
        Self {
            pki_data_reference,
            cert_references,
            replace,
            cert_template,
        }
    }
}

impl DERParseable for EnrollmentMessageSyntax2009ModCertTemplate {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let pki_data_reference = crate::EnrollmentMessageSyntax2009BodyPartPath::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let cert_references = crate::EnrollmentMessageSyntax2009BodyPartList::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let replace = ASN1Boolean::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let cert_template = crate::PKIXCRMF2009CertTemplate::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                pki_data_reference: pki_data_reference,
                cert_references: cert_references,
                replace: replace,
                cert_template: cert_template,
            })

        })
    }
}

impl DERSerializable for EnrollmentMessageSyntax2009ModCertTemplate {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
