// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct EnrollmentMessageSyntax2009ControlsProcessed {
    pub body_list: Vec<EnrollmentMessageSyntax2009BodyPartReference>,
}

impl EnrollmentMessageSyntax2009ControlsProcessed {
    pub fn new(body_list: Vec<EnrollmentMessageSyntax2009BodyPartReference>) -> Self {
        Self {
            body_list,
        }
    }
}

impl DERParseable for EnrollmentMessageSyntax2009ControlsProcessed {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let body_list: Vec<EnrollmentMessageSyntax2009BodyPartReference> = { let node = nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?; if let rust_asn1::asn1::Content::Constructed(collection) = node.content { collection.clone().into_iter().map(|child| EnrollmentMessageSyntax2009BodyPartReference::from_der_node(child)).collect::<Result<_, _>>()? } else { return Err(ASN1Error::new(rust_asn1::errors::ErrorCode::UnexpectedFieldType, "Expected constructed".to_string(), file!().to_string(), line!())); } };
            Ok(Self {
                body_list: body_list,
            })

        })
    }
}

impl DERSerializable for EnrollmentMessageSyntax2009ControlsProcessed {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
