// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct EnrollmentMessageSyntax2009GetCRL {
    pub issuer_name: crate::PKIX1Explicit2009Name,
    pub c_rl_name: Option<crate::PKIX1Implicit2009GeneralName>,
    pub time: Option<GeneralizedTime>,
    pub reasons: Option<crate::PKIX1Implicit2009ReasonFlags>,
}

impl EnrollmentMessageSyntax2009GetCRL {
    pub fn new(issuer_name: crate::PKIX1Explicit2009Name, c_rl_name: Option<crate::PKIX1Implicit2009GeneralName>, time: Option<GeneralizedTime>, reasons: Option<crate::PKIX1Implicit2009ReasonFlags>) -> Self {
        Self {
            issuer_name,
            c_rl_name,
            time,
            reasons,
        }
    }
}

impl DERParseable for EnrollmentMessageSyntax2009GetCRL {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let issuer_name = crate::PKIX1Explicit2009Name::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let c_rl_name: Option<crate::PKIX1Implicit2009GeneralName> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIX1Implicit2009GeneralName::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let time: Option<GeneralizedTime> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match GeneralizedTime::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let reasons: Option<crate::PKIX1Implicit2009ReasonFlags> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIX1Implicit2009ReasonFlags::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                issuer_name: issuer_name,
                c_rl_name: c_rl_name,
                time: time,
                reasons: reasons,
            })

        })
    }
}

impl DERSerializable for EnrollmentMessageSyntax2009GetCRL {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
