// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum InformationFrameworkChopSpecificationSpecificExclusionsChoice {
    ChopBefore(crate::InformationFrameworkLocalName),
    ChopAfter(crate::InformationFrameworkLocalName),
}

impl DERParseable for InformationFrameworkChopSpecificationSpecificExclusionsChoice {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (113, TagClass::ContextSpecific) => Ok(Self::ChopBefore(crate::InformationFrameworkLocalName::from_der_node(node)?)),
            (114, TagClass::ContextSpecific) => Ok(Self::ChopAfter(crate::InformationFrameworkLocalName::from_der_node(node)?)),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for InformationFrameworkChopSpecificationSpecificExclusionsChoice {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

