// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct ISOSTANDARD9541FONTATTRIBUTESETAdjustProperties {
    pub isostandard9541cpea: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETCPEAProperties>,
    pub isostandard9541sec: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETSECProperties>,
    pub nonisoproperties: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList>,
}

impl ISOSTANDARD9541FONTATTRIBUTESETAdjustProperties {
    pub fn new(isostandard9541cpea: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETCPEAProperties>, isostandard9541sec: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETSECProperties>, nonisoproperties: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList>) -> Self {
        Self {
            isostandard9541cpea,
            isostandard9541sec,
            nonisoproperties,
        }
    }
}

impl DERParseable for ISOSTANDARD9541FONTATTRIBUTESETAdjustProperties {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let isostandard9541cpea: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETCPEAProperties> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::ISOSTANDARD9541FONTATTRIBUTESETCPEAProperties::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let isostandard9541sec: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETSECProperties> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::ISOSTANDARD9541FONTATTRIBUTESETSECProperties::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let nonisoproperties: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                isostandard9541cpea: isostandard9541cpea,
                isostandard9541sec: isostandard9541sec,
                nonisoproperties: nonisoproperties,
            })

        })
    }
}

impl DERSerializable for ISOSTANDARD9541FONTATTRIBUTESETAdjustProperties {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
