// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct LayoutDescriptorsPositionSpec {
    pub offset: Option<crate::LayoutDescriptorsPositionSpecOffsetSet>,
    pub separation: Option<crate::LayoutDescriptorsPositionSpecSeparationSet>,
    pub alignment: Option<ASN1Integer>,
    pub fillorder: Option<ASN1Integer>,
}

impl LayoutDescriptorsPositionSpec {
    pub fn new(offset: Option<crate::LayoutDescriptorsPositionSpecOffsetSet>, separation: Option<crate::LayoutDescriptorsPositionSpecSeparationSet>, alignment: Option<ASN1Integer>, fillorder: Option<ASN1Integer>) -> Self {
        Self {
            offset,
            separation,
            alignment,
            fillorder,
        }
    }
}

impl DERParseable for LayoutDescriptorsPositionSpec {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let offset: Option<crate::LayoutDescriptorsPositionSpecOffsetSet> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LayoutDescriptorsPositionSpecOffsetSet::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let separation: Option<crate::LayoutDescriptorsPositionSpecSeparationSet> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LayoutDescriptorsPositionSpecSeparationSet::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let alignment: Option<ASN1Integer> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1Integer::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let fillorder: Option<ASN1Integer> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1Integer::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                offset: offset,
                separation: separation,
                alignment: alignment,
                fillorder: fillorder,
            })

        })
    }
}

impl DERSerializable for LayoutDescriptorsPositionSpec {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
