// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct LocationExpressionsObjectClassWithArgument {
    pub attribute_value_object: crate::LocationExpressionsAttributeValueClassSpecification,
    pub defaulting: ASN1Boolean,
}

impl LocationExpressionsObjectClassWithArgument {
    pub fn new(attribute_value_object: crate::LocationExpressionsAttributeValueClassSpecification, defaulting: ASN1Boolean) -> Self {
        Self {
            attribute_value_object,
            defaulting,
        }
    }
}

impl DERParseable for LocationExpressionsObjectClassWithArgument {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let attribute_value_object = crate::LocationExpressionsAttributeValueClassSpecification::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let defaulting = ASN1Boolean::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                attribute_value_object: attribute_value_object,
                defaulting: defaulting,
            })

        })
    }
}

impl DERSerializable for LocationExpressionsObjectClassWithArgument {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
