// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct LocationExpressionsContentWithArgument {
    pub attribute_value_content: crate::LocationExpressionsAttributeValueContentSpecification,
    pub component: Option<crate::LocationExpressionsComponentLocator>,
    pub counters: Option<crate::LocationExpressionsCountersType>,
    pub notdefaulting: ASN1Boolean,
}

impl LocationExpressionsContentWithArgument {
    pub fn new(attribute_value_content: crate::LocationExpressionsAttributeValueContentSpecification, component: Option<crate::LocationExpressionsComponentLocator>, counters: Option<crate::LocationExpressionsCountersType>, notdefaulting: ASN1Boolean) -> Self {
        Self {
            attribute_value_content,
            component,
            counters,
            notdefaulting,
        }
    }
}

impl DERParseable for LocationExpressionsContentWithArgument {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let attribute_value_content = crate::LocationExpressionsAttributeValueContentSpecification::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let component: Option<crate::LocationExpressionsComponentLocator> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LocationExpressionsComponentLocator::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let counters: Option<crate::LocationExpressionsCountersType> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LocationExpressionsCountersType::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let notdefaulting = ASN1Boolean::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                attribute_value_content: attribute_value_content,
                component: component,
                counters: counters,
                notdefaulting: notdefaulting,
            })

        })
    }
}

impl DERSerializable for LocationExpressionsContentWithArgument {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
