// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct LogicalDescriptorsLogicalObjectDescriptorBody {
    pub objectidentifier: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier>,
    pub subordinates: Option<Vec<ASN1NumericString>>,
    pub contentportions: Option<Vec<ASN1NumericString>>,
    pub objectclass: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier>,
    pub presentationattributes: Option<crate::StyleDescriptorsPresentationAttributes>,
    pub defaultvaluelists: Option<crate::DefaultValueListsLogical>,
    pub userreadablecomments: Option<crate::LayoutDescriptorsCommentString>,
    pub bindings: Option<Vec<LayoutDescriptorsBindingPair>>,
    pub contentgenerator: Option<crate::IdentifiersAndExpressionsStringExpression>,
    pub uservisiblename: Option<crate::LayoutDescriptorsCommentString>,
    pub presentationstyle: Option<crate::IdentifiersAndExpressionsStyleIdentifier>,
    pub layoutstyle: Option<crate::IdentifiersAndExpressionsStyleIdentifier>,
    pub protection: Option<crate::LogicalDescriptorsProtection>,
    pub applicationcomments: Option<ASN1OctetString>,
    pub primary: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier>,
    pub alternative: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier>,
    pub enciphered: Option<crate::LayoutDescriptorsEnciphered>,
    pub sealed: Option<crate::LayoutDescriptorsSealed>,
    pub temporalrelations: Option<crate::TemporalRelationshipsTemporalRelations>,
}

impl LogicalDescriptorsLogicalObjectDescriptorBody {
    pub fn new(objectidentifier: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier>, subordinates: Option<Vec<ASN1NumericString>>, contentportions: Option<Vec<ASN1NumericString>>, objectclass: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier>, presentationattributes: Option<crate::StyleDescriptorsPresentationAttributes>, defaultvaluelists: Option<crate::DefaultValueListsLogical>, userreadablecomments: Option<crate::LayoutDescriptorsCommentString>, bindings: Option<Vec<LayoutDescriptorsBindingPair>>, contentgenerator: Option<crate::IdentifiersAndExpressionsStringExpression>, uservisiblename: Option<crate::LayoutDescriptorsCommentString>, presentationstyle: Option<crate::IdentifiersAndExpressionsStyleIdentifier>, layoutstyle: Option<crate::IdentifiersAndExpressionsStyleIdentifier>, protection: Option<crate::LogicalDescriptorsProtection>, applicationcomments: Option<ASN1OctetString>, primary: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier>, alternative: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier>, enciphered: Option<crate::LayoutDescriptorsEnciphered>, sealed: Option<crate::LayoutDescriptorsSealed>, temporalrelations: Option<crate::TemporalRelationshipsTemporalRelations>) -> Self {
        Self {
            objectidentifier,
            subordinates,
            contentportions,
            objectclass,
            presentationattributes,
            defaultvaluelists,
            userreadablecomments,
            bindings,
            contentgenerator,
            uservisiblename,
            presentationstyle,
            layoutstyle,
            protection,
            applicationcomments,
            primary,
            alternative,
            enciphered,
            sealed,
            temporalrelations,
        }
    }
}

impl DERParseable for LogicalDescriptorsLogicalObjectDescriptorBody {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let objectidentifier: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::IdentifiersAndExpressionsObjectOrClassIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let subordinates: Option<Vec<ASN1NumericString>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ASN1NumericString::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let contentportions: Option<Vec<ASN1NumericString>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ASN1NumericString::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let objectclass: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::IdentifiersAndExpressionsObjectOrClassIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let presentationattributes: Option<crate::StyleDescriptorsPresentationAttributes> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::StyleDescriptorsPresentationAttributes::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let defaultvaluelists: Option<crate::DefaultValueListsLogical> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DefaultValueListsLogical::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let userreadablecomments: Option<crate::LayoutDescriptorsCommentString> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LayoutDescriptorsCommentString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let bindings: Option<Vec<LayoutDescriptorsBindingPair>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| LayoutDescriptorsBindingPair::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let contentgenerator: Option<crate::IdentifiersAndExpressionsStringExpression> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::IdentifiersAndExpressionsStringExpression::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let uservisiblename: Option<crate::LayoutDescriptorsCommentString> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LayoutDescriptorsCommentString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let presentationstyle: Option<crate::IdentifiersAndExpressionsStyleIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::IdentifiersAndExpressionsStyleIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let layoutstyle: Option<crate::IdentifiersAndExpressionsStyleIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::IdentifiersAndExpressionsStyleIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let protection: Option<crate::LogicalDescriptorsProtection> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LogicalDescriptorsProtection::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let applicationcomments: Option<ASN1OctetString> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1OctetString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let primary: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::IdentifiersAndExpressionsObjectOrClassIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let alternative: Option<crate::IdentifiersAndExpressionsObjectOrClassIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::IdentifiersAndExpressionsObjectOrClassIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let enciphered: Option<crate::LayoutDescriptorsEnciphered> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LayoutDescriptorsEnciphered::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let sealed: Option<crate::LayoutDescriptorsSealed> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LayoutDescriptorsSealed::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let temporalrelations: Option<crate::TemporalRelationshipsTemporalRelations> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::TemporalRelationshipsTemporalRelations::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                objectidentifier: objectidentifier,
                subordinates: subordinates,
                contentportions: contentportions,
                objectclass: objectclass,
                presentationattributes: presentationattributes,
                defaultvaluelists: defaultvaluelists,
                userreadablecomments: userreadablecomments,
                bindings: bindings,
                contentgenerator: contentgenerator,
                uservisiblename: uservisiblename,
                presentationstyle: presentationstyle,
                layoutstyle: layoutstyle,
                protection: protection,
                applicationcomments: applicationcomments,
                primary: primary,
                alternative: alternative,
                enciphered: enciphered,
                sealed: sealed,
                temporalrelations: temporalrelations,
            })

        })
    }
}

impl DERSerializable for LogicalDescriptorsLogicalObjectDescriptorBody {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
