// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct OCSPSingleResponse {
    pub cert_id: crate::OCSPCertID,
    pub cert_status: crate::OCSPCertStatus,
    pub this_update: GeneralizedTime,
    pub next_update: Option<GeneralizedTime>,
    pub single_extensions: Option<crate::PKIX1Explicit88Extensions>,
}

impl OCSPSingleResponse {
    pub fn new(cert_id: crate::OCSPCertID, cert_status: crate::OCSPCertStatus, this_update: GeneralizedTime, next_update: Option<GeneralizedTime>, single_extensions: Option<crate::PKIX1Explicit88Extensions>) -> Self {
        Self {
            cert_id,
            cert_status,
            this_update,
            next_update,
            single_extensions,
        }
    }
}

impl DERParseable for OCSPSingleResponse {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let cert_id = crate::OCSPCertID::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let cert_status = crate::OCSPCertStatus::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let this_update = GeneralizedTime::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let next_update: Option<GeneralizedTime> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match GeneralizedTime::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let single_extensions: Option<crate::PKIX1Explicit88Extensions> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIX1Explicit88Extensions::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                cert_id: cert_id,
                cert_status: cert_status,
                this_update: this_update,
                next_update: next_update,
                single_extensions: single_extensions,
            })

        })
    }
}

impl DERSerializable for OCSPSingleResponse {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
