// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKCS7EncryptedData {
    pub version: ASN1Integer,
    pub encrypted_content_info: crate::PKCS7EncryptedContentInfo,
}

impl PKCS7EncryptedData {
    pub fn new(version: ASN1Integer, encrypted_content_info: crate::PKCS7EncryptedContentInfo) -> Self {
        Self {
            version,
            encrypted_content_info,
        }
    }
}

impl DERParseable for PKCS7EncryptedData {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let version = ASN1Integer::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let encrypted_content_info = crate::PKCS7EncryptedContentInfo::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                version: version,
                encrypted_content_info: encrypted_content_info,
            })

        })
    }
}

impl DERSerializable for PKCS7EncryptedData {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
