// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKCS7SignedData {
    pub version: ASN1Integer,
    pub digest_algorithms: crate::PKCS7DigestAlgorithmIdentifiers,
    pub content_info: crate::PKCS7ContentInfo,
    pub certificates: Option<crate::PKCS7SignedDataCertificatesChoice>,
    pub crls: Option<crate::PKCS7SignedDataCrlsChoice>,
    pub signer_infos: crate::PKCS7SignerInfos,
}

impl PKCS7SignedData {
    pub fn new(version: ASN1Integer, digest_algorithms: crate::PKCS7DigestAlgorithmIdentifiers, content_info: crate::PKCS7ContentInfo, certificates: Option<crate::PKCS7SignedDataCertificatesChoice>, crls: Option<crate::PKCS7SignedDataCrlsChoice>, signer_infos: crate::PKCS7SignerInfos) -> Self {
        Self {
            version,
            digest_algorithms,
            content_info,
            certificates,
            crls,
            signer_infos,
        }
    }
}

impl DERParseable for PKCS7SignedData {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let version = ASN1Integer::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let digest_algorithms = crate::PKCS7DigestAlgorithmIdentifiers::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let content_info = crate::PKCS7ContentInfo::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let certificates: Option<crate::PKCS7SignedDataCertificatesChoice> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKCS7SignedDataCertificatesChoice::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let crls: Option<crate::PKCS7SignedDataCrlsChoice> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKCS7SignedDataCrlsChoice::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let signer_infos = crate::PKCS7SignerInfos::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                version: version,
                digest_algorithms: digest_algorithms,
                content_info: content_info,
                certificates: certificates,
                crls: crls,
                signer_infos: signer_infos,
            })

        })
    }
}

impl DERSerializable for PKCS7SignedData {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
