// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIXX400Address2009BuiltInDomainDefinedAttribute {
    pub type_: ASN1PrintableString,
    pub value: ASN1PrintableString,
}

impl PKIXX400Address2009BuiltInDomainDefinedAttribute {
    pub fn new(type_: ASN1PrintableString, value: ASN1PrintableString) -> Self {
        Self {
            type_,
            value,
        }
    }
}

impl DERParseable for PKIXX400Address2009BuiltInDomainDefinedAttribute {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let type_ = ASN1PrintableString::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let value = ASN1PrintableString::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                type_: type_,
                value: value,
            })

        })
    }
}

impl DERSerializable for PKIXX400Address2009BuiltInDomainDefinedAttribute {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
