// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIXCMP2009PKIStatusInfo {
    pub status: crate::PKIXCMP2009PKIStatus,
    pub status_string: Option<crate::PKIXCMP2009PKIFreeText>,
    pub fail_info: Option<crate::PKIXCMP2009PKIFailureInfo>,
}

impl PKIXCMP2009PKIStatusInfo {
    pub fn new(status: crate::PKIXCMP2009PKIStatus, status_string: Option<crate::PKIXCMP2009PKIFreeText>, fail_info: Option<crate::PKIXCMP2009PKIFailureInfo>) -> Self {
        Self {
            status,
            status_string,
            fail_info,
        }
    }
}

impl DERParseable for PKIXCMP2009PKIStatusInfo {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let status = crate::PKIXCMP2009PKIStatus::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let status_string: Option<crate::PKIXCMP2009PKIFreeText> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIXCMP2009PKIFreeText::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let fail_info: Option<crate::PKIXCMP2009PKIFailureInfo> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIXCMP2009PKIFailureInfo::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                status: status,
                status_string: status_string,
                fail_info: fail_info,
            })

        })
    }
}

impl DERSerializable for PKIXCMP2009PKIStatusInfo {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
