// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIXCRMF2009PrivateKeyInfo {
    pub version: ASN1Integer,
    pub private_key_algorithm: crate::AlgorithmInformation2009Algorithm,
    pub private_key: ASN1OctetString,
    pub attributes: Option<crate::PKIXCRMF2009Attributes>,
}

impl PKIXCRMF2009PrivateKeyInfo {
    pub fn new(version: ASN1Integer, private_key_algorithm: crate::AlgorithmInformation2009Algorithm, private_key: ASN1OctetString, attributes: Option<crate::PKIXCRMF2009Attributes>) -> Self {
        Self {
            version,
            private_key_algorithm,
            private_key,
            attributes,
        }
    }
}

impl DERParseable for PKIXCRMF2009PrivateKeyInfo {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let version = ASN1Integer::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let private_key_algorithm = crate::AlgorithmInformation2009Algorithm::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let private_key = ASN1OctetString::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let attributes: Option<crate::PKIXCRMF2009Attributes> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIXCRMF2009Attributes::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                version: version,
                private_key_algorithm: private_key_algorithm,
                private_key: private_key,
                attributes: attributes,
            })

        })
    }
}

impl DERSerializable for PKIXCRMF2009PrivateKeyInfo {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
