// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIXAttributeCertificate2009ClearanceRfc3281 {
    pub policy_id: ASN1ObjectIdentifier,
    pub class_list: crate::PKIXAttributeCertificate2009ClassList,
    pub security_categories: Option<Vec<PKIXAttributeCertificate2009SecurityCategoryRfc3281>>,
}

impl PKIXAttributeCertificate2009ClearanceRfc3281 {
    pub fn new(policy_id: ASN1ObjectIdentifier, class_list: crate::PKIXAttributeCertificate2009ClassList, security_categories: Option<Vec<PKIXAttributeCertificate2009SecurityCategoryRfc3281>>) -> Self {
        Self {
            policy_id,
            class_list,
            security_categories,
        }
    }
}

impl DERParseable for PKIXAttributeCertificate2009ClearanceRfc3281 {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let policy_id = ASN1ObjectIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let class_list = crate::PKIXAttributeCertificate2009ClassList::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let security_categories: Option<Vec<PKIXAttributeCertificate2009SecurityCategoryRfc3281>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| PKIXAttributeCertificate2009SecurityCategoryRfc3281::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            Ok(Self {
                policy_id: policy_id,
                class_list: class_list,
                security_categories: security_categories,
            })

        })
    }
}

impl DERSerializable for PKIXAttributeCertificate2009ClearanceRfc3281 {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
