// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIX1Implicit88GeneralSubtree {
    pub base: crate::PKIX1Implicit88GeneralName,
    pub minimum: crate::PKIX1Implicit88BaseDistance,
    pub maximum: Option<crate::PKIX1Implicit88BaseDistance>,
}

impl PKIX1Implicit88GeneralSubtree {
    pub fn new(base: crate::PKIX1Implicit88GeneralName, minimum: crate::PKIX1Implicit88BaseDistance, maximum: Option<crate::PKIX1Implicit88BaseDistance>) -> Self {
        Self {
            base,
            minimum,
            maximum,
        }
    }
}

impl DERParseable for PKIX1Implicit88GeneralSubtree {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let base = crate::PKIX1Implicit88GeneralName::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let minimum = crate::PKIX1Implicit88BaseDistance::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let maximum: Option<crate::PKIX1Implicit88BaseDistance> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIX1Implicit88BaseDistance::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                base: base,
                minimum: minimum,
                maximum: maximum,
            })

        })
    }
}

impl DERSerializable for PKIX1Implicit88GeneralSubtree {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
