// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIX1Implicit88DistributionPoint {
    pub distribution_point: Option<crate::PKIX1Implicit88DistributionPointName>,
    pub reasons: Option<crate::PKIX1Implicit88ReasonFlags>,
    pub c_rl_issuer: Option<crate::PKIX1Implicit88GeneralNames>,
}

impl PKIX1Implicit88DistributionPoint {
    pub fn new(distribution_point: Option<crate::PKIX1Implicit88DistributionPointName>, reasons: Option<crate::PKIX1Implicit88ReasonFlags>, c_rl_issuer: Option<crate::PKIX1Implicit88GeneralNames>) -> Self {
        Self {
            distribution_point,
            reasons,
            c_rl_issuer,
        }
    }
}

impl DERParseable for PKIX1Implicit88DistributionPoint {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let distribution_point: Option<crate::PKIX1Implicit88DistributionPointName> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIX1Implicit88DistributionPointName::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let reasons: Option<crate::PKIX1Implicit88ReasonFlags> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIX1Implicit88ReasonFlags::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let c_rl_issuer: Option<crate::PKIX1Implicit88GeneralNames> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIX1Implicit88GeneralNames::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                distribution_point: distribution_point,
                reasons: reasons,
                c_rl_issuer: c_rl_issuer,
            })

        })
    }
}

impl DERSerializable for PKIX1Implicit88DistributionPoint {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
