  // Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum RasterGrPresentationAttributesPelTransmissionDensity {
    P5 = 2,
    P4 = 3,
    P3 = 4,
    P2 = 5,
    P1 = 6,
    ColourGreyScaleP12 = 10,
    ColourGreyScaleP6 = 11,
    ColourGreyScaleP4 = 13,
    ColourGreyScaleP3 = 14,
    ColourGreyScaleP2 = 15,
    ColourGreyScaleP1 = 16,
    P6 = 1,
}

impl DERParseable for RasterGrPresentationAttributesPelTransmissionDensity {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        let integer = ASN1Integer::from_der_node(node)?;
        // Attempt to convert BigInt to i64
        // ASN1Integer usually wraps BigInt in `value`.
        // We need to import TryInto or use a conversion method.
        // Using `TryInto` requires `use std::convert::TryInto;` in scope or prelude.
        // If `ASN1Integer` doesn't impl `TryInto<i64>`, maybe `integer.value` does.
        // Assuming `integer.value` is BigInt and `num_traits` or similar is available via `rust-asn1`.
        // If not available, we can try formatting to string and parsing (slow but robust fallback?).
        // Or assume `try_into` works on `value`.
        // Error said: `required for ASN1Integer to implement TryInto`. So `integer.try_into()` failed.
        // Let's try `integer.value.try_into()`.
        let val_res: Result<i64, _> = integer.value.try_into();
        let val = val_res.map_err(|_| ASN1Error::new(rust_asn1::errors::ErrorCode::InvalidASN1Object, "Enum value out of range".to_string(), file!().to_string(), line!()))?;
        match val {
            2 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::P5),
            3 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::P4),
            4 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::P3),
            5 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::P2),
            6 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::P1),
            10 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::ColourGreyScaleP12),
            11 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::ColourGreyScaleP6),
            13 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::ColourGreyScaleP4),
            14 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::ColourGreyScaleP3),
            15 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::ColourGreyScaleP2),
            16 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::ColourGreyScaleP1),
            1 => Ok(RasterGrPresentationAttributesPelTransmissionDensity::P6),
            _ => Err(ASN1Error::new(rust_asn1::errors::ErrorCode::InvalidASN1Object, format!("Unknown value for RasterGrPresentationAttributesPelTransmissionDensity: {}", val), file!().to_string(), line!()))
        }
    }
}

impl DERSerializable for RasterGrPresentationAttributesPelTransmissionDensity {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

