// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct SMIMESymmetricKeyDistribution2009GLOwnerInfo {
    pub gl_owner_name: crate::PKIX1Implicit2009GeneralName,
    pub gl_owner_address: crate::PKIX1Implicit2009GeneralName,
    pub certificates: Option<crate::SMIMESymmetricKeyDistribution2009Certificates>,
}

impl SMIMESymmetricKeyDistribution2009GLOwnerInfo {
    pub fn new(gl_owner_name: crate::PKIX1Implicit2009GeneralName, gl_owner_address: crate::PKIX1Implicit2009GeneralName, certificates: Option<crate::SMIMESymmetricKeyDistribution2009Certificates>) -> Self {
        Self {
            gl_owner_name,
            gl_owner_address,
            certificates,
        }
    }
}

impl DERParseable for SMIMESymmetricKeyDistribution2009GLOwnerInfo {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let gl_owner_name = crate::PKIX1Implicit2009GeneralName::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let gl_owner_address = crate::PKIX1Implicit2009GeneralName::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let certificates: Option<crate::SMIMESymmetricKeyDistribution2009Certificates> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::SMIMESymmetricKeyDistribution2009Certificates::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                gl_owner_name: gl_owner_name,
                gl_owner_address: gl_owner_address,
                certificates: certificates,
            })

        })
    }
}

impl DERSerializable for SMIMESymmetricKeyDistribution2009GLOwnerInfo {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
