// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum StyleDescriptorsSameLayoutObjectLayoutObjectChoice {
    D(crate::IdentifiersAndExpressionsObjectOrClassIdentifier),
    ToStreamRootCategory(crate::IdentifiersAndExpressionsCategoryName),
    ToStreamSubCategory(crate::IdentifiersAndExpressionsCategoryName),
    ToLayoutCategory(crate::IdentifiersAndExpressionsCategoryName),
    E(crate::LayoutDescriptorsLayoutObjectType),
}

impl DERParseable for StyleDescriptorsSameLayoutObjectLayoutObjectChoice {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (137, TagClass::ContextSpecific) => Ok(Self::D(crate::IdentifiersAndExpressionsObjectOrClassIdentifier::from_der_node(node)?)),
            (138, TagClass::ContextSpecific) => Ok(Self::ToStreamRootCategory(crate::IdentifiersAndExpressionsCategoryName::from_der_node(node)?)),
            (139, TagClass::ContextSpecific) => Ok(Self::ToStreamSubCategory(crate::IdentifiersAndExpressionsCategoryName::from_der_node(node)?)),
            (140, TagClass::ContextSpecific) => Ok(Self::ToLayoutCategory(crate::IdentifiersAndExpressionsCategoryName::from_der_node(node)?)),
            (141, TagClass::ContextSpecific) => Ok(Self::E(crate::LayoutDescriptorsLayoutObjectType::from_der_node(node)?)),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for StyleDescriptorsSameLayoutObjectLayoutObjectChoice {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

