// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct TemporalRelationshipsPresentationTime {
    pub timing: Option<crate::TemporalRelationshipsPresentationTimeTimingChoice>,
    pub duration: Option<crate::TemporalRelationshipsPresentationTimeDurationChoice>,
    pub cyclic: Option<crate::TemporalRelationshipsCyclic>,
}

impl TemporalRelationshipsPresentationTime {
    pub fn new(timing: Option<crate::TemporalRelationshipsPresentationTimeTimingChoice>, duration: Option<crate::TemporalRelationshipsPresentationTimeDurationChoice>, cyclic: Option<crate::TemporalRelationshipsCyclic>) -> Self {
        Self {
            timing,
            duration,
            cyclic,
        }
    }
}

impl DERParseable for TemporalRelationshipsPresentationTime {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let timing: Option<crate::TemporalRelationshipsPresentationTimeTimingChoice> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::TemporalRelationshipsPresentationTimeTimingChoice::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let duration: Option<crate::TemporalRelationshipsPresentationTimeDurationChoice> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::TemporalRelationshipsPresentationTimeDurationChoice::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let cyclic: Option<crate::TemporalRelationshipsCyclic> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::TemporalRelationshipsCyclic::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                timing: timing,
                duration: duration,
                cyclic: cyclic,
            })

        })
    }
}

impl DERSerializable for TemporalRelationshipsPresentationTime {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
