  // Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum GeoGrPresentationAttributesTextRenditionTextPathEnum {
    Right = 0,
    Left = 1,
    Up = 2,
    Down = 3,
}

impl DERParseable for GeoGrPresentationAttributesTextRenditionTextPathEnum {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        let integer = ASN1Integer::from_der_node(node)?;
        // Attempt to convert BigInt to i64
        // ASN1Integer usually wraps BigInt in `value`.
        // We need to import TryInto or use a conversion method.
        // Using `TryInto` requires `use std::convert::TryInto;` in scope or prelude.
        // If `ASN1Integer` doesn't impl `TryInto<i64>`, maybe `integer.value` does.
        // Assuming `integer.value` is BigInt and `num_traits` or similar is available via `rust-asn1`.
        // If not available, we can try formatting to string and parsing (slow but robust fallback?).
        // Or assume `try_into` works on `value`.
        // Error said: `required for ASN1Integer to implement TryInto`. So `integer.try_into()` failed.
        // Let's try `integer.value.try_into()`.
        let val_res: Result<i64, _> = integer.value.try_into();
        let val = val_res.map_err(|_| ASN1Error::new(rust_asn1::errors::ErrorCode::InvalidASN1Object, "Enum value out of range".to_string(), file!().to_string(), line!()))?;
        match val {
            0 => Ok(GeoGrPresentationAttributesTextRenditionTextPathEnum::Right),
            1 => Ok(GeoGrPresentationAttributesTextRenditionTextPathEnum::Left),
            2 => Ok(GeoGrPresentationAttributesTextRenditionTextPathEnum::Up),
            3 => Ok(GeoGrPresentationAttributesTextRenditionTextPathEnum::Down),
            _ => Err(ASN1Error::new(rust_asn1::errors::ErrorCode::InvalidASN1Object, format!("Unknown value for GeoGrPresentationAttributesTextRenditionTextPathEnum: {}", val), file!().to_string(), line!()))
        }
    }
}

impl DERSerializable for GeoGrPresentationAttributesTextRenditionTextPathEnum {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

