// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum CryptographicMessageSyntax2010RevocationInfoChoice {
    Crl(crate::PKIX1Explicit2009CertificateList),

    Other(crate::CryptographicMessageSyntax2010OtherRevocationInfoFormat),
}

impl DERParseable for CryptographicMessageSyntax2010RevocationInfoChoice {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (319, TagClass::ContextSpecific) => Ok(Self::Crl(crate::PKIX1Explicit2009CertificateList::from_der_node(node)?)),
            (321, TagClass::ContextSpecific) => Ok(Self::Other(crate::CryptographicMessageSyntax2010OtherRevocationInfoFormat::from_der_node(node)?)),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for CryptographicMessageSyntax2010RevocationInfoChoice {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

