// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIXCMP2009OOBCertHash {
    pub hash_alg: Option<crate::AlgorithmInformation2009Algorithm>,
    pub cert_id: Option<crate::PKIXCRMF2009CertId>,
    pub hash_val: ASN1BitString,
}

impl PKIXCMP2009OOBCertHash {
    pub fn new(hash_alg: Option<crate::AlgorithmInformation2009Algorithm>, cert_id: Option<crate::PKIXCRMF2009CertId>, hash_val: ASN1BitString) -> Self {
        Self {
            hash_alg,
            cert_id,
            hash_val,
        }
    }
}

impl DERParseable for PKIXCMP2009OOBCertHash {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let hash_alg: Option<crate::AlgorithmInformation2009Algorithm> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::AlgorithmInformation2009Algorithm::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let cert_id: Option<crate::PKIXCRMF2009CertId> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIXCRMF2009CertId::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let hash_val = ASN1BitString::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                hash_alg: hash_alg,
                cert_id: cert_id,
                hash_val: hash_val,
            })

        })
    }
}

impl DERSerializable for PKIXCMP2009OOBCertHash {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
