// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct CMSAESCCMAndAESGCM2009CCMParameters {
    pub aesnonce: ASN1OctetString,
    pub aes_ic_vlen: crate::CMSAESCCMAndAESGCM2009AESCCMICVlen,
}

impl CMSAESCCMAndAESGCM2009CCMParameters {
    pub fn new(aesnonce: ASN1OctetString, aes_ic_vlen: crate::CMSAESCCMAndAESGCM2009AESCCMICVlen) -> Self {
        Self {
            aesnonce,
            aes_ic_vlen,
        }
    }
}

impl DERParseable for CMSAESCCMAndAESGCM2009CCMParameters {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let aesnonce = ASN1OctetString::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let aes_ic_vlen = crate::CMSAESCCMAndAESGCM2009AESCCMICVlen::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                aesnonce: aesnonce,
                aes_ic_vlen: aes_ic_vlen,
            })

        })
    }
}

impl DERSerializable for CMSAESCCMAndAESGCM2009CCMParameters {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
