// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct DocumentProfileDescriptorAdditionalInformation {
    pub descriptiveinformation: Option<crate::DocumentProfileDescriptorCharacterData>,
    pub octetstring: Option<ASN1OctetString>,
}

impl DocumentProfileDescriptorAdditionalInformation {
    pub fn new(descriptiveinformation: Option<crate::DocumentProfileDescriptorCharacterData>, octetstring: Option<ASN1OctetString>) -> Self {
        Self {
            descriptiveinformation,
            octetstring,
        }
    }
}

impl DERParseable for DocumentProfileDescriptorAdditionalInformation {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let descriptiveinformation: Option<crate::DocumentProfileDescriptorCharacterData> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorCharacterData::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let octetstring: Option<ASN1OctetString> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1OctetString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                descriptiveinformation: descriptiveinformation,
                octetstring: octetstring,
            })

        })
    }
}

impl DERSerializable for DocumentProfileDescriptorAdditionalInformation {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
