// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct DocumentProfileDescriptorDocumentCharacteristics {
    pub documentapplicationprofile: Option<crate::DocumentProfileDescriptorDocumentCharacteristicsDocumentApplicationProfileChoice>,
    pub docapplprofiledefaults: Option<crate::DocumentProfileDescriptorDocApplProfileDefaults>,
    pub documentarchitectureclass: ASN1Integer,
    pub contentarchitectureclasses: Vec<ASN1ObjectIdentifier>,
    pub interchangeformatclass: ASN1Integer,
    pub odaversion: crate::DocumentProfileDescriptorODAVersion,
    pub alternativefeaturesets: Option<Vec<Vec<ASN1ObjectIdentifier>>>,
    pub nonbasicdoccharacteristics: Option<crate::DocumentProfileDescriptorNonBasicDocCharacteristics>,
    pub nonbasicstruccharacteristics: Option<crate::DocumentProfileDescriptorNonBasicStrucCharacteristics>,
    pub additionaldoccharacteristics: Option<crate::DocumentProfileDescriptorAdditionalDocCharacteristics>,
}

impl DocumentProfileDescriptorDocumentCharacteristics {
    pub fn new(documentapplicationprofile: Option<crate::DocumentProfileDescriptorDocumentCharacteristicsDocumentApplicationProfileChoice>, docapplprofiledefaults: Option<crate::DocumentProfileDescriptorDocApplProfileDefaults>, documentarchitectureclass: ASN1Integer, contentarchitectureclasses: Vec<ASN1ObjectIdentifier>, interchangeformatclass: ASN1Integer, odaversion: crate::DocumentProfileDescriptorODAVersion, alternativefeaturesets: Option<Vec<Vec<ASN1ObjectIdentifier>>>, nonbasicdoccharacteristics: Option<crate::DocumentProfileDescriptorNonBasicDocCharacteristics>, nonbasicstruccharacteristics: Option<crate::DocumentProfileDescriptorNonBasicStrucCharacteristics>, additionaldoccharacteristics: Option<crate::DocumentProfileDescriptorAdditionalDocCharacteristics>) -> Self {
        Self {
            documentapplicationprofile,
            docapplprofiledefaults,
            documentarchitectureclass,
            contentarchitectureclasses,
            interchangeformatclass,
            odaversion,
            alternativefeaturesets,
            nonbasicdoccharacteristics,
            nonbasicstruccharacteristics,
            additionaldoccharacteristics,
        }
    }
}

impl DERParseable for DocumentProfileDescriptorDocumentCharacteristics {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let documentapplicationprofile: Option<crate::DocumentProfileDescriptorDocumentCharacteristicsDocumentApplicationProfileChoice> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorDocumentCharacteristicsDocumentApplicationProfileChoice::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let docapplprofiledefaults: Option<crate::DocumentProfileDescriptorDocApplProfileDefaults> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorDocApplProfileDefaults::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let documentarchitectureclass = ASN1Integer::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let contentarchitectureclasses: Vec<ASN1ObjectIdentifier> = { let node = nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?; if let rust_asn1::asn1::Content::Constructed(collection) = node.content { collection.clone().into_iter().map(|child| ASN1ObjectIdentifier::from_der_node(child)).collect::<Result<_, _>>()? } else { return Err(ASN1Error::new(rust_asn1::errors::ErrorCode::UnexpectedFieldType, "Expected constructed".to_string(), file!().to_string(), line!())); } };
            let interchangeformatclass = ASN1Integer::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let odaversion = crate::DocumentProfileDescriptorODAVersion::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let alternativefeaturesets: Option<Vec<Vec<ASN1ObjectIdentifier>>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| Vec::<ASN1ObjectIdentifier>::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let nonbasicdoccharacteristics: Option<crate::DocumentProfileDescriptorNonBasicDocCharacteristics> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorNonBasicDocCharacteristics::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let nonbasicstruccharacteristics: Option<crate::DocumentProfileDescriptorNonBasicStrucCharacteristics> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorNonBasicStrucCharacteristics::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let additionaldoccharacteristics: Option<crate::DocumentProfileDescriptorAdditionalDocCharacteristics> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorAdditionalDocCharacteristics::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                documentapplicationprofile: documentapplicationprofile,
                docapplprofiledefaults: docapplprofiledefaults,
                documentarchitectureclass: documentarchitectureclass,
                contentarchitectureclasses: contentarchitectureclasses,
                interchangeformatclass: interchangeformatclass,
                odaversion: odaversion,
                alternativefeaturesets: alternativefeaturesets,
                nonbasicdoccharacteristics: nonbasicdoccharacteristics,
                nonbasicstruccharacteristics: nonbasicstruccharacteristics,
                additionaldoccharacteristics: additionaldoccharacteristics,
            })

        })
    }
}

impl DERSerializable for DocumentProfileDescriptorDocumentCharacteristics {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
