// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct DocumentProfileDescriptorPrivRecipientsInfo {
    pub privilegedrecipients: Option<Vec<DocumentProfileDescriptorPersonalName>>,
    pub enciphermentmethodinfo: Option<crate::DocumentProfileDescriptorMethodInformation>,
    pub enciphermentkeyinfo: Option<crate::DocumentProfileDescriptorKeyInformation>,
}

impl DocumentProfileDescriptorPrivRecipientsInfo {
    pub fn new(privilegedrecipients: Option<Vec<DocumentProfileDescriptorPersonalName>>, enciphermentmethodinfo: Option<crate::DocumentProfileDescriptorMethodInformation>, enciphermentkeyinfo: Option<crate::DocumentProfileDescriptorKeyInformation>) -> Self {
        Self {
            privilegedrecipients,
            enciphermentmethodinfo,
            enciphermentkeyinfo,
        }
    }
}

impl DERParseable for DocumentProfileDescriptorPrivRecipientsInfo {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let privilegedrecipients: Option<Vec<DocumentProfileDescriptorPersonalName>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| DocumentProfileDescriptorPersonalName::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let enciphermentmethodinfo: Option<crate::DocumentProfileDescriptorMethodInformation> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorMethodInformation::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let enciphermentkeyinfo: Option<crate::DocumentProfileDescriptorKeyInformation> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorKeyInformation::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                privilegedrecipients: privilegedrecipients,
                enciphermentmethodinfo: enciphermentmethodinfo,
                enciphermentkeyinfo: enciphermentkeyinfo,
            })

        })
    }
}

impl DERSerializable for DocumentProfileDescriptorPrivRecipientsInfo {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
