// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct DocumentProfileDescriptorOriginators {
    pub organizations: Option<Vec<DocumentProfileDescriptorCharacterData>>,
    pub preparers: Option<Vec<ASN1Node>>,
    pub owners: Option<Vec<ASN1Node>>,
    pub authors: Option<Vec<ASN1Node>>,
}

impl DocumentProfileDescriptorOriginators {
    pub fn new(organizations: Option<Vec<DocumentProfileDescriptorCharacterData>>, preparers: Option<Vec<ASN1Node>>, owners: Option<Vec<ASN1Node>>, authors: Option<Vec<ASN1Node>>) -> Self {
        Self {
            organizations,
            preparers,
            owners,
            authors,
        }
    }
}

impl DERParseable for DocumentProfileDescriptorOriginators {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let organizations: Option<Vec<DocumentProfileDescriptorCharacterData>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| DocumentProfileDescriptorCharacterData::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let preparers: Option<Vec<ASN1Node>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); Some(collection.clone().into_iter().collect::<Vec<ASN1Node>>()) } else { None } } else { None };
            let owners: Option<Vec<ASN1Node>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); Some(collection.clone().into_iter().collect::<Vec<ASN1Node>>()) } else { None } } else { None };
            let authors: Option<Vec<ASN1Node>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); Some(collection.clone().into_iter().collect::<Vec<ASN1Node>>()) } else { None } } else { None };
            Ok(Self {
                organizations: organizations,
                preparers: preparers,
                owners: owners,
                authors: authors,
            })

        })
    }
}

impl DERSerializable for DocumentProfileDescriptorOriginators {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
