// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct DocumentProfileDescriptorLocalFileReferencesElement {
    pub filename: Option<crate::DocumentProfileDescriptorCharacterData>,
    pub location: Option<crate::DocumentProfileDescriptorCharacterData>,
    pub usercomments: Option<crate::DocumentProfileDescriptorCharacterData>,
}

impl DocumentProfileDescriptorLocalFileReferencesElement {
    pub fn new(filename: Option<crate::DocumentProfileDescriptorCharacterData>, location: Option<crate::DocumentProfileDescriptorCharacterData>, usercomments: Option<crate::DocumentProfileDescriptorCharacterData>) -> Self {
        Self {
            filename,
            location,
            usercomments,
        }
    }
}

impl DERParseable for DocumentProfileDescriptorLocalFileReferencesElement {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let filename: Option<crate::DocumentProfileDescriptorCharacterData> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorCharacterData::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let location: Option<crate::DocumentProfileDescriptorCharacterData> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorCharacterData::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let usercomments: Option<crate::DocumentProfileDescriptorCharacterData> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorCharacterData::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                filename: filename,
                location: location,
                usercomments: usercomments,
            })

        })
    }
}

impl DERSerializable for DocumentProfileDescriptorLocalFileReferencesElement {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
