// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct DocumentProfileDescriptorDatesAndTimesRevisionHistorySetRevisersSet {
    pub names: Option<Vec<DocumentProfileDescriptorPersonalName>>,
    pub position: Option<crate::DocumentProfileDescriptorCharacterData>,
    pub organization: Option<crate::DocumentProfileDescriptorCharacterData>,
}

impl DocumentProfileDescriptorDatesAndTimesRevisionHistorySetRevisersSet {
    pub fn new(names: Option<Vec<DocumentProfileDescriptorPersonalName>>, position: Option<crate::DocumentProfileDescriptorCharacterData>, organization: Option<crate::DocumentProfileDescriptorCharacterData>) -> Self {
        Self {
            names,
            position,
            organization,
        }
    }
}

impl DERParseable for DocumentProfileDescriptorDatesAndTimesRevisionHistorySetRevisersSet {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let names: Option<Vec<DocumentProfileDescriptorPersonalName>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| DocumentProfileDescriptorPersonalName::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let position: Option<crate::DocumentProfileDescriptorCharacterData> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorCharacterData::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let organization: Option<crate::DocumentProfileDescriptorCharacterData> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorCharacterData::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                names: names,
                position: position,
                organization: organization,
            })

        })
    }
}

impl DERSerializable for DocumentProfileDescriptorDatesAndTimesRevisionHistorySetRevisersSet {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
