// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIX1Explicit88CertificateList {
    pub tbs_cert_list: PKIX1Explicit88TBSCertList,
    pub signature_algorithm: PKIX1Explicit88AlgorithmIdentifier,
    pub signature: ASN1BitString,
}

impl PKIX1Explicit88CertificateList {
    pub fn new(tbs_cert_list: PKIX1Explicit88TBSCertList, signature_algorithm: PKIX1Explicit88AlgorithmIdentifier, signature: ASN1BitString) -> Self {
        Self {
            tbs_cert_list,
            signature_algorithm,
            signature,
        }
    }
}

impl DERParseable for PKIX1Explicit88CertificateList {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let tbs_cert_list = PKIX1Explicit88TBSCertList::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let signature_algorithm = PKIX1Explicit88AlgorithmIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let signature = ASN1BitString::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                tbs_cert_list: tbs_cert_list,
                signature_algorithm: signature_algorithm,
                signature: signature,
            })

        })
    }
}

impl DERSerializable for PKIX1Explicit88CertificateList {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
