// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum LocationExpressionsContentPortionLocator {
    ContentPortion(crate::IdentifiersAndExpressionsContentPortionIdentifier),
    Assoc(crate::LocationExpressionsAssocArgument),
    ContentWith(crate::LocationExpressionsContentWithArgument),
}

impl DERParseable for LocationExpressionsContentPortionLocator {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (164, TagClass::ContextSpecific) => Ok(Self::ContentPortion(crate::IdentifiersAndExpressionsContentPortionIdentifier::from_der_node(node)?)),
            (165, TagClass::ContextSpecific) => Ok(Self::Assoc(crate::LocationExpressionsAssocArgument::from_der_node(node)?)),
            (166, TagClass::ContextSpecific) => Ok(Self::ContentWith(crate::LocationExpressionsContentWithArgument::from_der_node(node)?)),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for LocationExpressionsContentPortionLocator {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

