  // Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum LocationExpressionsConstituentType {
    LayoutObjectClass = 1,
    LayoutObject = 2,
    ContentPortion = 3,
    LogicalObjectClass = 5,
    LogicalObject = 6,
    PresentationStyle = 7,
    LayoutStyle = 8,
    SealedDocProfDescriptor = 9,
    EncipheredDocProfDescriptor = 10,
    PreencipheredBodypartDescriptor = 11,
    PostencipheredBodypartDescriptor = 12,
    LinkClass = 13,
    Link = 14,
    EncipheredLinkDescriptor = 15,
    Subprofile = 16,
}

impl DERParseable for LocationExpressionsConstituentType {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        let integer = ASN1Integer::from_der_node(node)?;
        // Attempt to convert BigInt to i64
        // ASN1Integer usually wraps BigInt in `value`.
        // We need to import TryInto or use a conversion method.
        // Using `TryInto` requires `use std::convert::TryInto;` in scope or prelude.
        // If `ASN1Integer` doesn't impl `TryInto<i64>`, maybe `integer.value` does.
        // Assuming `integer.value` is BigInt and `num_traits` or similar is available via `rust-asn1`.
        // If not available, we can try formatting to string and parsing (slow but robust fallback?).
        // Or assume `try_into` works on `value`.
        // Error said: `required for ASN1Integer to implement TryInto`. So `integer.try_into()` failed.
        // Let's try `integer.value.try_into()`.
        let val_res: Result<i64, _> = integer.value.try_into();
        let val = val_res.map_err(|_| ASN1Error::new(rust_asn1::errors::ErrorCode::InvalidASN1Object, "Enum value out of range".to_string(), file!().to_string(), line!()))?;
        match val {
            1 => Ok(LocationExpressionsConstituentType::LayoutObjectClass),
            2 => Ok(LocationExpressionsConstituentType::LayoutObject),
            3 => Ok(LocationExpressionsConstituentType::ContentPortion),
            5 => Ok(LocationExpressionsConstituentType::LogicalObjectClass),
            6 => Ok(LocationExpressionsConstituentType::LogicalObject),
            7 => Ok(LocationExpressionsConstituentType::PresentationStyle),
            8 => Ok(LocationExpressionsConstituentType::LayoutStyle),
            9 => Ok(LocationExpressionsConstituentType::SealedDocProfDescriptor),
            10 => Ok(LocationExpressionsConstituentType::EncipheredDocProfDescriptor),
            11 => Ok(LocationExpressionsConstituentType::PreencipheredBodypartDescriptor),
            12 => Ok(LocationExpressionsConstituentType::PostencipheredBodypartDescriptor),
            13 => Ok(LocationExpressionsConstituentType::LinkClass),
            14 => Ok(LocationExpressionsConstituentType::Link),
            15 => Ok(LocationExpressionsConstituentType::EncipheredLinkDescriptor),
            16 => Ok(LocationExpressionsConstituentType::Subprofile),
            _ => Err(ASN1Error::new(rust_asn1::errors::ErrorCode::InvalidASN1Object, format!("Unknown value for LocationExpressionsConstituentType: {}", val), file!().to_string(), line!()))
        }
    }
}

impl DERSerializable for LocationExpressionsConstituentType {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

