// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct DirectoryAbstractServiceSecurityParameters {
    pub certificationpath: Option<crate::AuthenticationFrameworkCertificationPath>,
    pub name: Option<crate::InformationFrameworkDistinguishedName>,
    pub time: Option<crate::DirectoryAbstractServiceTime>,
    pub random: Option<ASN1BitString>,
    pub target: Option<crate::DirectoryAbstractServiceProtectionRequest>,
    pub response: Option<ASN1BitString>,
    pub operation_code: Option<crate::DirectoryAbstractServiceCode>,
    pub attribute_certification_path: Option<crate::AuthenticationFrameworkAttributeCertificationPath>,
    pub error_protection: Option<crate::DirectoryAbstractServiceErrorProtectionRequest>,
    pub error_code: Option<crate::DirectoryAbstractServiceCode>,
}

impl DirectoryAbstractServiceSecurityParameters {
    pub fn new(certificationpath: Option<crate::AuthenticationFrameworkCertificationPath>, name: Option<crate::InformationFrameworkDistinguishedName>, time: Option<crate::DirectoryAbstractServiceTime>, random: Option<ASN1BitString>, target: Option<crate::DirectoryAbstractServiceProtectionRequest>, response: Option<ASN1BitString>, operation_code: Option<crate::DirectoryAbstractServiceCode>, attribute_certification_path: Option<crate::AuthenticationFrameworkAttributeCertificationPath>, error_protection: Option<crate::DirectoryAbstractServiceErrorProtectionRequest>, error_code: Option<crate::DirectoryAbstractServiceCode>) -> Self {
        Self {
            certificationpath,
            name,
            time,
            random,
            target,
            response,
            operation_code,
            attribute_certification_path,
            error_protection,
            error_code,
        }
    }
}

impl DERParseable for DirectoryAbstractServiceSecurityParameters {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let certificationpath: Option<crate::AuthenticationFrameworkCertificationPath> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::AuthenticationFrameworkCertificationPath::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let name: Option<crate::InformationFrameworkDistinguishedName> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::InformationFrameworkDistinguishedName::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let time: Option<crate::DirectoryAbstractServiceTime> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DirectoryAbstractServiceTime::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let random: Option<ASN1BitString> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1BitString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let target: Option<crate::DirectoryAbstractServiceProtectionRequest> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DirectoryAbstractServiceProtectionRequest::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let response: Option<ASN1BitString> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1BitString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let operation_code: Option<crate::DirectoryAbstractServiceCode> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DirectoryAbstractServiceCode::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let attribute_certification_path: Option<crate::AuthenticationFrameworkAttributeCertificationPath> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::AuthenticationFrameworkAttributeCertificationPath::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let error_protection: Option<crate::DirectoryAbstractServiceErrorProtectionRequest> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DirectoryAbstractServiceErrorProtectionRequest::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let error_code: Option<crate::DirectoryAbstractServiceCode> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DirectoryAbstractServiceCode::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                certificationpath: certificationpath,
                name: name,
                time: time,
                random: random,
                target: target,
                response: response,
                operation_code: operation_code,
                attribute_certification_path: attribute_certification_path,
                error_protection: error_protection,
                error_code: error_code,
            })

        })
    }
}

impl DERSerializable for DirectoryAbstractServiceSecurityParameters {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
