// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum DirectoryAbstractServiceFilterItemSubstringsSequenceStringsChoice {
    Initial(ASN1Node),
    Any(ASN1Node),
    Final(ASN1Node),
    Control(crate::InformationFrameworkAttribute),
}

impl DERParseable for DirectoryAbstractServiceFilterItemSubstringsSequenceStringsChoice {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (163, TagClass::ContextSpecific) => Ok(Self::Initial(node)),
            (164, TagClass::ContextSpecific) => Ok(Self::Any(node)),
            (165, TagClass::ContextSpecific) => Ok(Self::Final(node)),
            (166, TagClass::ContextSpecific) => Ok(Self::Control(crate::InformationFrameworkAttribute::from_der_node(node)?)),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for DirectoryAbstractServiceFilterItemSubstringsSequenceStringsChoice {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

