// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum ColourAttributesColourSpecification {
    CmykColour(crate::ColourAttributesCMYKColour),
    RgbColour(crate::ColourAttributesRGBColour),
    CieColour(crate::ColourAttributesCIEColour),
}

impl DERParseable for ColourAttributesColourSpecification {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (28, TagClass::ContextSpecific) => Ok(Self::CmykColour(crate::ColourAttributesCMYKColour::from_der_node(node)?)),
            (29, TagClass::ContextSpecific) => Ok(Self::RgbColour(crate::ColourAttributesRGBColour::from_der_node(node)?)),
            (30, TagClass::ContextSpecific) => Ok(Self::CieColour(crate::ColourAttributesCIEColour::from_der_node(node)?)),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for ColourAttributesColourSpecification {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

