// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct ColourAttributesColourTableEntry {
    pub index: ASN1Integer,
    pub r: crate::ColourAttributesRealOrInt,
    pub g: crate::ColourAttributesRealOrInt,
    pub b: crate::ColourAttributesRealOrInt,
}

impl ColourAttributesColourTableEntry {
    pub fn new(index: ASN1Integer, r: crate::ColourAttributesRealOrInt, g: crate::ColourAttributesRealOrInt, b: crate::ColourAttributesRealOrInt) -> Self {
        Self {
            index,
            r,
            g,
            b,
        }
    }
}

impl DERParseable for ColourAttributesColourTableEntry {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let index = ASN1Integer::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let r = crate::ColourAttributesRealOrInt::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let g = crate::ColourAttributesRealOrInt::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let b = crate::ColourAttributesRealOrInt::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                index: index,
                r: r,
                g: g,
                b: b,
            })

        })
    }
}

impl DERSerializable for ColourAttributesColourTableEntry {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
