// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct ISO9541SNStructuredName {
    pub ownername: Option<crate::ISO9541SNOwnerName>,
    pub ownerdescription: Option<crate::ISO9541SNMessage>,
    pub objectname: Option<Vec<ISO9541SNObjectNameComponent>>,
    pub objectdescription: Option<crate::ISO9541SNMessage>,
}

impl ISO9541SNStructuredName {
    pub fn new(ownername: Option<crate::ISO9541SNOwnerName>, ownerdescription: Option<crate::ISO9541SNMessage>, objectname: Option<Vec<ISO9541SNObjectNameComponent>>, objectdescription: Option<crate::ISO9541SNMessage>) -> Self {
        Self {
            ownername,
            ownerdescription,
            objectname,
            objectdescription,
        }
    }
}

impl DERParseable for ISO9541SNStructuredName {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let ownername: Option<crate::ISO9541SNOwnerName> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::ISO9541SNOwnerName::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let ownerdescription: Option<crate::ISO9541SNMessage> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::ISO9541SNMessage::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let objectname: Option<Vec<ISO9541SNObjectNameComponent>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ISO9541SNObjectNameComponent::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let objectdescription: Option<crate::ISO9541SNMessage> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::ISO9541SNMessage::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                ownername: ownername,
                ownerdescription: ownerdescription,
                objectname: objectname,
                objectdescription: objectdescription,
            })

        })
    }
}

impl DERSerializable for ISO9541SNStructuredName {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
