// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct ISO9541SNOwnerName {
    pub object_identifier: Option<ASN1ObjectIdentifier>,
    pub owner_name_component: Option<Vec<ISO9541SNOwnerNameComponent>>,
}

impl ISO9541SNOwnerName {
    pub fn new(object_identifier: Option<ASN1ObjectIdentifier>, owner_name_component: Option<Vec<ISO9541SNOwnerNameComponent>>) -> Self {
        Self {
            object_identifier,
            owner_name_component,
        }
    }
}

impl DERParseable for ISO9541SNOwnerName {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let object_identifier: Option<ASN1ObjectIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1ObjectIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let owner_name_component: Option<Vec<ISO9541SNOwnerNameComponent>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ISO9541SNOwnerNameComponent::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            Ok(Self {
                object_identifier: object_identifier,
                owner_name_component: owner_name_component,
            })

        })
    }
}

impl DERSerializable for ISO9541SNOwnerName {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
