// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct SubprofilesDatesAndTimesRevisionHistorySet {
    pub revisiondateandtime: Option<crate::DocumentProfileDescriptorDateAndTime>,
    pub versionidentifier: Option<crate::DocumentProfileDescriptorCharacterData>,
    pub revisers: Option<Vec<ASN1Node>>,
    pub versionreference: Option<crate::SubprofilesDocumentOrDocumentFragmentReference>,
    pub usercomments: Option<crate::DocumentProfileDescriptorCharacterData>,
}

impl SubprofilesDatesAndTimesRevisionHistorySet {
    pub fn new(revisiondateandtime: Option<crate::DocumentProfileDescriptorDateAndTime>, versionidentifier: Option<crate::DocumentProfileDescriptorCharacterData>, revisers: Option<Vec<ASN1Node>>, versionreference: Option<crate::SubprofilesDocumentOrDocumentFragmentReference>, usercomments: Option<crate::DocumentProfileDescriptorCharacterData>) -> Self {
        Self {
            revisiondateandtime,
            versionidentifier,
            revisers,
            versionreference,
            usercomments,
        }
    }
}

impl DERParseable for SubprofilesDatesAndTimesRevisionHistorySet {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let revisiondateandtime: Option<crate::DocumentProfileDescriptorDateAndTime> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorDateAndTime::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let versionidentifier: Option<crate::DocumentProfileDescriptorCharacterData> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorCharacterData::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let revisers: Option<Vec<ASN1Node>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); Some(collection.clone().into_iter().collect::<Vec<ASN1Node>>()) } else { None } } else { None };
            let versionreference: Option<crate::SubprofilesDocumentOrDocumentFragmentReference> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::SubprofilesDocumentOrDocumentFragmentReference::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let usercomments: Option<crate::DocumentProfileDescriptorCharacterData> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DocumentProfileDescriptorCharacterData::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                revisiondateandtime: revisiondateandtime,
                versionidentifier: versionidentifier,
                revisers: revisers,
                versionreference: versionreference,
                usercomments: usercomments,
            })

        })
    }
}

impl DERSerializable for SubprofilesDatesAndTimesRevisionHistorySet {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
