// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct SubprofilesExternalReferences2 {
    pub referencestootherdocumentsordocumentfragments: Option<Vec<SubprofilesDocumentOrDocumentFragmentReference>>,
    pub supersededdocumentsordocumentfragments: Option<Vec<SubprofilesDocumentOrDocumentFragmentReference>>,
}

impl SubprofilesExternalReferences2 {
    pub fn new(referencestootherdocumentsordocumentfragments: Option<Vec<SubprofilesDocumentOrDocumentFragmentReference>>, supersededdocumentsordocumentfragments: Option<Vec<SubprofilesDocumentOrDocumentFragmentReference>>) -> Self {
        Self {
            referencestootherdocumentsordocumentfragments,
            supersededdocumentsordocumentfragments,
        }
    }
}

impl DERParseable for SubprofilesExternalReferences2 {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let referencestootherdocumentsordocumentfragments: Option<Vec<SubprofilesDocumentOrDocumentFragmentReference>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| SubprofilesDocumentOrDocumentFragmentReference::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let supersededdocumentsordocumentfragments: Option<Vec<SubprofilesDocumentOrDocumentFragmentReference>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| SubprofilesDocumentOrDocumentFragmentReference::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            Ok(Self {
                referencestootherdocumentsordocumentfragments: referencestootherdocumentsordocumentfragments,
                supersededdocumentsordocumentfragments: supersededdocumentsordocumentfragments,
            })

        })
    }
}

impl DERSerializable for SubprofilesExternalReferences2 {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
