// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum PKIX1Implicit2009GeneralName {
    OtherName(ASN1Node),
    Rfc822Name(ASN1IA5String),
    DNSName(ASN1IA5String),
    X400Address(ASN1Node),
    DirectoryName(crate::PKIX1Explicit2009Name),
    EdiPartyName(crate::PKIX1Implicit2009EDIPartyName),
    UniformResourceIdentifier(ASN1IA5String),
    IPAddress(ASN1OctetString),
    RegisteredID(ASN1ObjectIdentifier),
}

impl DERParseable for PKIX1Implicit2009GeneralName {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (185, TagClass::ContextSpecific) => Ok(Self::OtherName(node)),
            (186, TagClass::ContextSpecific) => Ok(Self::Rfc822Name(ASN1IA5String::from_der_node(node)?)),
            (187, TagClass::ContextSpecific) => Ok(Self::DNSName(ASN1IA5String::from_der_node(node)?)),
            (188, TagClass::ContextSpecific) => Ok(Self::X400Address(node)),
            (189, TagClass::ContextSpecific) => Ok(Self::DirectoryName(crate::PKIX1Explicit2009Name::from_der_node(node)?)),
            (190, TagClass::ContextSpecific) => Ok(Self::EdiPartyName(crate::PKIX1Implicit2009EDIPartyName::from_der_node(node)?)),
            (191, TagClass::ContextSpecific) => Ok(Self::UniformResourceIdentifier(ASN1IA5String::from_der_node(node)?)),
            (192, TagClass::ContextSpecific) => Ok(Self::IPAddress(ASN1OctetString::from_der_node(node)?)),
            (193, TagClass::ContextSpecific) => Ok(Self::RegisteredID(ASN1ObjectIdentifier::from_der_node(node)?)),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for PKIX1Implicit2009GeneralName {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

