// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct CertificateExtensionsNameConstraintsSyntax {
    pub permitted_subtrees: Option<CertificateExtensionsGeneralSubtrees>,
    pub excluded_subtrees: Option<CertificateExtensionsGeneralSubtrees>,
    pub required_name_forms: Option<CertificateExtensionsNameForms>,
}

impl CertificateExtensionsNameConstraintsSyntax {
    pub fn new(permitted_subtrees: Option<CertificateExtensionsGeneralSubtrees>, excluded_subtrees: Option<CertificateExtensionsGeneralSubtrees>, required_name_forms: Option<CertificateExtensionsNameForms>) -> Self {
        Self {
            permitted_subtrees,
            excluded_subtrees,
            required_name_forms,
        }
    }
}

impl DERParseable for CertificateExtensionsNameConstraintsSyntax {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let permitted_subtrees: Option<CertificateExtensionsGeneralSubtrees> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match CertificateExtensionsGeneralSubtrees::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let excluded_subtrees: Option<CertificateExtensionsGeneralSubtrees> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match CertificateExtensionsGeneralSubtrees::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let required_name_forms: Option<CertificateExtensionsNameForms> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match CertificateExtensionsNameForms::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                permitted_subtrees: permitted_subtrees,
                excluded_subtrees: excluded_subtrees,
                required_name_forms: required_name_forms,
            })

        })
    }
}

impl DERSerializable for CertificateExtensionsNameConstraintsSyntax {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
