// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct CertificateExtensionsSupportedAlgorithm {
    pub algorithm_identifier: AuthenticationFrameworkAlgorithmIdentifier,
    pub intended_usage: Option<CertificateExtensionsKeyUsage>,
    pub intended_certificate_policies: Option<CertificateExtensionsCertificatePoliciesSyntax>,
}

impl CertificateExtensionsSupportedAlgorithm {
    pub fn new(algorithm_identifier: AuthenticationFrameworkAlgorithmIdentifier, intended_usage: Option<CertificateExtensionsKeyUsage>, intended_certificate_policies: Option<CertificateExtensionsCertificatePoliciesSyntax>) -> Self {
        Self {
            algorithm_identifier,
            intended_usage,
            intended_certificate_policies,
        }
    }
}

impl DERParseable for CertificateExtensionsSupportedAlgorithm {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let algorithm_identifier = AuthenticationFrameworkAlgorithmIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let intended_usage: Option<CertificateExtensionsKeyUsage> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match CertificateExtensionsKeyUsage::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let intended_certificate_policies: Option<CertificateExtensionsCertificatePoliciesSyntax> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match CertificateExtensionsCertificatePoliciesSyntax::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                algorithm_identifier: algorithm_identifier,
                intended_usage: intended_usage,
                intended_certificate_policies: intended_certificate_policies,
            })

        })
    }
}

impl DERSerializable for CertificateExtensionsSupportedAlgorithm {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
