// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Server: Equatable, Hashable, Codable, Sendable {
    @usableFromInline var service: ASN1OctetString
    @usableFromInline var port: Int
    @usableFromInline var host: ASN1OctetString
    @inlinable init(service: ASN1OctetString, port: Int, host: ASN1OctetString) {
        self.service = service
        self.port = port
        self.host = host
    }

    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
            self.service = try DER.decode(ASN1OctetString.self)
            self.port = try DER.decode(Int.self)
            self.host = try DER.decode(ASN1OctetString.self)
    }

    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
            try coder.serialize(service)
            try coder.serialize(port)
            try coder.serialize(host)
    }

}
