// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline enum CHAT_MemberStatus: Int, ASN1Enumerated, Equatable, Hashable, Codable, Sendable {
    case admin = 1
    case member = 2
    case removed = 3
    case patch = 4
    case owner = 5
}
