// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_P2P: Equatable, Hashable, Codable, Sendable {
    @usableFromInline var src: ASN1OctetString
    @usableFromInline var dst: ASN1OctetString
    @inlinable init(src: ASN1OctetString, dst: ASN1OctetString) {
        self.src = src
        self.dst = dst
    }

    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
            self.src = try DER.decode(ASN1OctetString.self)
            self.dst = try DER.decode(ASN1OctetString.self)
    }

    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
            try coder.serialize(src)
            try coder.serialize(dst)
    }

}
