// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Search: Equatable, Hashable, Codable, Sendable {
    @usableFromInline var dn: ASN1OctetString
    @usableFromInline var id: ASN1OctetString
    @usableFromInline var field: ASN1OctetString
    @usableFromInline var value: ASN1OctetString
    @usableFromInline var criteria: CHAT_Criteria
    @usableFromInline var type: CHAT_Scope
    @usableFromInline var status: CHAT_SearchStatus
    @inlinable init(dn: ASN1OctetString, id: ASN1OctetString, field: ASN1OctetString, value: ASN1OctetString, criteria: CHAT_Criteria, type: CHAT_Scope, status: CHAT_SearchStatus) {
        self.dn = dn
        self.id = id
        self.field = field
        self.value = value
        self.criteria = criteria
        self.type = type
        self.status = status
    }

    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
            self.dn = try DER.decode(ASN1OctetString.self)
            self.id = try DER.decode(ASN1OctetString.self)
            self.field = try DER.decode(ASN1OctetString.self)
            self.value = try DER.decode(ASN1OctetString.self)
            self.criteria = try DER.decode(CHAT_Criteria.self)
            self.type = try DER.decode(CHAT_Scope.self)
            self.status = try DER.decode(CHAT_SearchStatus.self)
    }

    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
            try coder.serialize(dn)
            try coder.serialize(id)
            try coder.serialize(field)
            try coder.serialize(value)
            try coder.serialize(criteria)
            try coder.serialize(type)
            try coder.serialize(status)
    }

}
