// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct CHAT_Member: Equatable, Hashable, Codable, Sendable {
    @usableFromInline var id: Int
    @usableFromInline var feed-id: CHAT_Member_feed-id_Choice
    @usableFromInline var feeds: [ASN1OctetString]
    @usableFromInline var phone-id: ASN1OctetString
    @usableFromInline var avatar: ASN1OctetString
    @usableFromInline var names: [ASN1OctetString]
    @usableFromInline var surnames: [ASN1OctetString]
    @usableFromInline var alias: ASN1OctetString
    @usableFromInline var update: Int
    @usableFromInline var settings: [CHAT_Feature]
    @usableFromInline var services: [CHAT_Service]
    @usableFromInline var presence: CHAT_PresenceType
    @usableFromInline var status: CHAT_MemberStatus
    @inlinable init(id: Int, feed-id: CHAT_Member_feed_id_Choice, feeds: [ASN1OctetString], phone-id: ASN1OctetString, avatar: ASN1OctetString, names: [ASN1OctetString], surnames: [ASN1OctetString], alias: ASN1OctetString, update: Int, settings: [CHAT_Feature], services: [CHAT_Service], presence: CHAT_PresenceType, status: CHAT_MemberStatus) {
        self.id = id
        self.feed-id = feed-id
        self.feeds = feeds
        self.phone-id = phone-id
        self.avatar = avatar
        self.names = names
        self.surnames = surnames
        self.alias = alias
        self.update = update
        self.settings = settings
        self.services = services
        self.presence = presence
        self.status = status
    }

    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
            self.id = try DER.decode(Int.self)
            self.feed-id = try DER.decode(CHAT_Member_feed_id_Choice.self)
            self.feeds = try DER.sequence(of: ASN1OctetString.self, identifier: .sequence, rootNode: rootNode)
            self.phone-id = try DER.decode(ASN1OctetString.self)
            self.avatar = try DER.decode(ASN1OctetString.self)
            self.names = try DER.sequence(of: ASN1OctetString.self, identifier: .sequence, rootNode: rootNode)
            self.surnames = try DER.sequence(of: ASN1OctetString.self, identifier: .sequence, rootNode: rootNode)
            self.alias = try DER.decode(ASN1OctetString.self)
            self.update = try DER.decode(Int.self)
            self.settings = try DER.sequence(of: CHAT_Feature.self, identifier: .sequence, rootNode: rootNode)
            self.services = try DER.sequence(of: CHAT_Service.self, identifier: .sequence, rootNode: rootNode)
            self.presence = try DER.decode(CHAT_PresenceType.self)
            self.status = try DER.decode(CHAT_MemberStatus.self)
    }

    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
            try coder.serialize(id)
            try coder.serialize(feed-id)
            try coder.serialize(feeds)
            try coder.serialize(phone-id)
            try coder.serialize(avatar)
            try coder.serialize(names)
            try coder.serialize(surnames)
            try coder.serialize(alias)
            try coder.serialize(update)
            try coder.serialize(settings)
            try coder.serialize(services)
            try coder.serialize(presence)
            try coder.serialize(status)
    }

}
