// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct DSTU_TBSCertificate: Equatable, Hashable, Codable, Sendable {
    @usableFromInline var version: DSTU_Version?
    @usableFromInline var serialNumber: DSTU_CertificateSerialNumber
    @usableFromInline var signature: DSTU_AlgorithmIdentifier
    @usableFromInline var issuer: DSTU_Name
    @usableFromInline var validity: DSTU_Validity
    @usableFromInline var subject: DSTU_Name
    @usableFromInline var subjectPublicKeyInfo: DSTU_SubjectPublicKeyInfo
    @usableFromInline var issuerUniqueID: DSTU_UniqueIdentifier?
    @usableFromInline var subjectUniqueID: DSTU_UniqueIdentifier?
    @usableFromInline var extensions: DSTU_Extensions?
    @inlinable init(version: DSTU_Version?, serialNumber: DSTU_CertificateSerialNumber, signature: DSTU_AlgorithmIdentifier, issuer: DSTU_Name, validity: DSTU_Validity, subject: DSTU_Name, subjectPublicKeyInfo: DSTU_SubjectPublicKeyInfo, issuerUniqueID: DSTU_UniqueIdentifier?, subjectUniqueID: DSTU_UniqueIdentifier?, extensions: DSTU_Extensions?) {
        self.version = version
        self.serialNumber = serialNumber
        self.signature = signature
        self.issuer = issuer
        self.validity = validity
        self.subject = subject
        self.subjectPublicKeyInfo = subjectPublicKeyInfo
        self.issuerUniqueID = issuerUniqueID
        self.subjectUniqueID = subjectUniqueID
        self.extensions = extensions
    }

    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
            self.version = try DER.decode(DSTU_Version.self)
            self.serialNumber = try DER.decode(DSTU_CertificateSerialNumber.self)
            self.signature = try DER.decode(DSTU_AlgorithmIdentifier.self)
            self.issuer = try DER.decode(DSTU_Name.self)
            self.validity = try DER.decode(DSTU_Validity.self)
            self.subject = try DER.decode(DSTU_Name.self)
            self.subjectPublicKeyInfo = try DER.decode(DSTU_SubjectPublicKeyInfo.self)
            self.issuerUniqueID = try DER.decode(DSTU_UniqueIdentifier.self)
            self.subjectUniqueID = try DER.decode(DSTU_UniqueIdentifier.self)
            self.extensions = try DER.decode(DSTU_Extensions.self)
    }

    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
            if let version = self.version { if let version = self.version { try coder.serialize(version) } }
            try coder.serialize(serialNumber)
            try coder.serialize(signature)
            try coder.serialize(issuer)
            try coder.serialize(validity)
            try coder.serialize(subject)
            try coder.serialize(subjectPublicKeyInfo)
            if let issuerUniqueID = self.issuerUniqueID { if let issuerUniqueID = self.issuerUniqueID { try coder.serialize(issuerUniqueID) } }
            if let subjectUniqueID = self.subjectUniqueID { if let subjectUniqueID = self.subjectUniqueID { try coder.serialize(subjectUniqueID) } }
            if let extensions = self.extensions { if let extensions = self.extensions { try coder.serialize(extensions) } }
    }

}
