// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct DSTU_BinaryField: Equatable, Hashable, Codable, Sendable {
    @usableFromInline var m: Int
    @usableFromInline var p: DSTU_BinaryField_p_Choice?
    @inlinable init(m: Int, p: DSTU_BinaryField_p_Choice?) {
        self.m = m
        self.p = p
    }

    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
            self.m = try DER.decode(Int.self)
            self.p = try DER.decode(DSTU_BinaryField_p_Choice.self)
    }

    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
            try coder.serialize(m)
            if let p = self.p { if let p = self.p { try coder.serialize(p) } }
    }

}
