// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct DSTU_Certificate: Equatable, Hashable, Codable, Sendable {
    @usableFromInline var tbsCertificate: DSTU_TBSCertificate
    @usableFromInline var signatureAlgorithm: DSTU_AlgorithmIdentifier
    @usableFromInline var signatureValue: ASN1BitString
    @inlinable init(tbsCertificate: DSTU_TBSCertificate, signatureAlgorithm: DSTU_AlgorithmIdentifier, signatureValue: ASN1BitString) {
        self.tbsCertificate = tbsCertificate
        self.signatureAlgorithm = signatureAlgorithm
        self.signatureValue = signatureValue
    }

    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
            self.tbsCertificate = try DER.decode(DSTU_TBSCertificate.self)
            self.signatureAlgorithm = try DER.decode(DSTU_AlgorithmIdentifier.self)
            self.signatureValue = try DER.decode(ASN1BitString.self)
    }

    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
            try coder.serialize(tbsCertificate)
            try coder.serialize(signatureAlgorithm)
            try coder.serialize(signatureValue)
    }

}
