// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import SwiftASN1
import Foundation

@usableFromInline struct LDAP_Control: Equatable, Hashable, Codable, Sendable {
    @usableFromInline var controlType: LDAP_LDAPOID
    @usableFromInline var criticality: Bool?
    @usableFromInline var controlValue: ASN1OctetString?
    @inlinable init(controlType: LDAP_LDAPOID, criticality: Bool?, controlValue: ASN1OctetString?) {
        self.controlType = controlType
        self.criticality = criticality
        self.controlValue = controlValue
    }

    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
            self.controlType = try DER.decode(LDAP_LDAPOID.self)
            self.criticality = try DER.decode(Bool.self)
            self.controlValue = try DER.decode(ASN1OctetString.self)
    }

    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
            try coder.serialize(controlType)
            if let criticality = self.criticality { if let criticality = self.criticality { try coder.serialize(criticality) } }
            if let controlValue = self.controlValue { if let controlValue = self.controlValue { try coder.serialize(controlValue) } }
    }

}
