// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct ANSIX942OtherInfo {
    pub key_info: crate::AuthenticationFrameworkAlgorithmIdentifier,
    pub party_u_info: Option<ASN1OctetString>,
    pub party_v_info: Option<ASN1OctetString>,
    pub supp_pub_info: Option<Box<ASN1OctetString>>,
    pub supp_priv_info: Option<Box<ASN1OctetString>>,
}

impl ANSIX942OtherInfo {
    pub fn new(key_info: crate::AuthenticationFrameworkAlgorithmIdentifier, party_u_info: Option<ASN1OctetString>, party_v_info: Option<ASN1OctetString>, supp_pub_info: Option<Box<ASN1OctetString>>, supp_priv_info: Option<Box<ASN1OctetString>>) -> Self {
        Self {
            key_info,
            party_u_info,
            party_v_info,
            supp_pub_info,
            supp_priv_info,
        }
    }
}

impl DERParseable for ANSIX942OtherInfo {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let key_info = crate::AuthenticationFrameworkAlgorithmIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let party_u_info: Option<ASN1OctetString> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1OctetString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let party_v_info: Option<ASN1OctetString> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1OctetString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let supp_pub_info: Option<Box<ASN1OctetString>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1OctetString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(Box::new(val)) }, Err(_) => None } } else { None };
            let supp_priv_info: Option<Box<ASN1OctetString>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1OctetString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(Box::new(val)) }, Err(_) => None } } else { None };
            Ok(Self {
                key_info: key_info,
                party_u_info: party_u_info,
                party_v_info: party_v_info,
                supp_pub_info: supp_pub_info,
                supp_priv_info: supp_priv_info,
            })

        })
    }
}

impl DERSerializable for ANSIX942OtherInfo {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
