// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum SelectedAttributeTypesCriteriaItem {
    Equality(PKIX1Explicit88AttributeType),
    Substrings(PKIX1Explicit88AttributeType),
    GreaterOrEqual(PKIX1Explicit88AttributeType),
    LessOrEqual(PKIX1Explicit88AttributeType),
    ApproximateMatch(PKIX1Explicit88AttributeType),
}

impl DERParseable for SelectedAttributeTypesCriteriaItem {
    fn from_der_node(_node: ASN1Node) -> Result<Self, ASN1Error> {
        // TODO: Switch on tags to decode specific variant
        todo!("DER decoding for choice SelectedAttributeTypesCriteriaItem")
    }
}

impl DERSerializable for SelectedAttributeTypesCriteriaItem {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

