// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct SelectedAttributeTypesFacsimileTelephoneNumber {
    pub telephone_number: SelectedAttributeTypesTelephoneNumber,
    pub parameters: Option<SelectedAttributeTypesG3FacsimileNonBasicParameters>,
}

impl SelectedAttributeTypesFacsimileTelephoneNumber {
    pub fn new(telephone_number: SelectedAttributeTypesTelephoneNumber, parameters: Option<SelectedAttributeTypesG3FacsimileNonBasicParameters>) -> Self {
        Self {
            telephone_number,
            parameters,
        }
    }
}

impl DERParseable for SelectedAttributeTypesFacsimileTelephoneNumber {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let telephone_number = SelectedAttributeTypesTelephoneNumber::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let parameters: Option<SelectedAttributeTypesG3FacsimileNonBasicParameters> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match SelectedAttributeTypesG3FacsimileNonBasicParameters::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                telephone_number: telephone_number,
                parameters: parameters,
            })

        })
    }
}

impl DERSerializable for SelectedAttributeTypesFacsimileTelephoneNumber {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
