// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIX1Explicit88Validity {
    pub not_before: crate::PKIX1Explicit88Time,
    pub not_after: crate::PKIX1Explicit88Time,
}

impl PKIX1Explicit88Validity {
    pub fn new(not_before: crate::PKIX1Explicit88Time, not_after: crate::PKIX1Explicit88Time) -> Self {
        Self {
            not_before,
            not_after,
        }
    }
}

impl DERParseable for PKIX1Explicit88Validity {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let not_before = crate::PKIX1Explicit88Time::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let not_after = crate::PKIX1Explicit88Time::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                not_before: not_before,
                not_after: not_after,
            })

        })
    }
}

impl DERSerializable for PKIX1Explicit88Validity {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
