// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIXAttributeCertificate2009AAControls {
    pub path_len_constraint: Option<ASN1Integer>,
    pub permitted_attrs: Option<crate::PKIXAttributeCertificate2009AttrSpec>,
    pub excluded_attrs: Option<crate::PKIXAttributeCertificate2009AttrSpec>,
    pub permit_un_specified: ASN1Boolean,
}

impl PKIXAttributeCertificate2009AAControls {
    pub fn new(path_len_constraint: Option<ASN1Integer>, permitted_attrs: Option<crate::PKIXAttributeCertificate2009AttrSpec>, excluded_attrs: Option<crate::PKIXAttributeCertificate2009AttrSpec>, permit_un_specified: ASN1Boolean) -> Self {
        Self {
            path_len_constraint,
            permitted_attrs,
            excluded_attrs,
            permit_un_specified,
        }
    }
}

impl DERParseable for PKIXAttributeCertificate2009AAControls {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let path_len_constraint: Option<ASN1Integer> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1Integer::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let permitted_attrs: Option<crate::PKIXAttributeCertificate2009AttrSpec> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIXAttributeCertificate2009AttrSpec::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let excluded_attrs: Option<crate::PKIXAttributeCertificate2009AttrSpec> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::PKIXAttributeCertificate2009AttrSpec::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let permit_un_specified = ASN1Boolean::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                path_len_constraint: path_len_constraint,
                permitted_attrs: permitted_attrs,
                excluded_attrs: excluded_attrs,
                permit_un_specified: permit_un_specified,
            })

        })
    }
}

impl DERSerializable for PKIXAttributeCertificate2009AAControls {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
