// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIXAttributeCertificate2009ACClearAttrs {
    pub ac_issuer: crate::PKIX1Implicit2009GeneralName,
    pub ac_serial: ASN1Integer,
    pub attrs: Vec<PKIXCommonTypes2009AttributeSet>,
}

impl PKIXAttributeCertificate2009ACClearAttrs {
    pub fn new(ac_issuer: crate::PKIX1Implicit2009GeneralName, ac_serial: ASN1Integer, attrs: Vec<PKIXCommonTypes2009AttributeSet>) -> Self {
        Self {
            ac_issuer,
            ac_serial,
            attrs,
        }
    }
}

impl DERParseable for PKIXAttributeCertificate2009ACClearAttrs {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let ac_issuer = crate::PKIX1Implicit2009GeneralName::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let ac_serial = ASN1Integer::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let attrs: Vec<PKIXCommonTypes2009AttributeSet> = { let node = nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?; if let rust_asn1::asn1::Content::Constructed(collection) = node.content { collection.clone().into_iter().map(|child| PKIXCommonTypes2009AttributeSet::from_der_node(child)).collect::<Result<_, _>>()? } else { return Err(ASN1Error::new(rust_asn1::errors::ErrorCode::UnexpectedFieldType, "Expected constructed".to_string(), file!().to_string(), line!())); } };
            Ok(Self {
                ac_issuer: ac_issuer,
                ac_serial: ac_serial,
                attrs: attrs,
            })

        })
    }
}

impl DERSerializable for PKIXAttributeCertificate2009ACClearAttrs {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
