// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct RasterGrPresentationAttributesCoordinatePair {
    pub xcoordinate: ASN1Integer,
    pub ycoordinate: ASN1Integer,
}

impl RasterGrPresentationAttributesCoordinatePair {
    pub fn new(xcoordinate: ASN1Integer, ycoordinate: ASN1Integer) -> Self {
        Self {
            xcoordinate,
            ycoordinate,
        }
    }
}

impl DERParseable for RasterGrPresentationAttributesCoordinatePair {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let xcoordinate = ASN1Integer::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let ycoordinate = ASN1Integer::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                xcoordinate: xcoordinate,
                ycoordinate: ycoordinate,
            })

        })
    }
}

impl DERSerializable for RasterGrPresentationAttributesCoordinatePair {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
