// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct LayoutDescriptorsBorder {
    pub lefthandedge: Option<crate::LayoutDescriptorsBorderEdge>,
    pub righthandedge: Option<crate::LayoutDescriptorsBorderEdge>,
    pub trailingedge: Option<crate::LayoutDescriptorsBorderEdge>,
    pub leadingedge: Option<crate::LayoutDescriptorsBorderEdge>,
}

impl LayoutDescriptorsBorder {
    pub fn new(lefthandedge: Option<crate::LayoutDescriptorsBorderEdge>, righthandedge: Option<crate::LayoutDescriptorsBorderEdge>, trailingedge: Option<crate::LayoutDescriptorsBorderEdge>, leadingedge: Option<crate::LayoutDescriptorsBorderEdge>) -> Self {
        Self {
            lefthandedge,
            righthandedge,
            trailingedge,
            leadingedge,
        }
    }
}

impl DERParseable for LayoutDescriptorsBorder {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let lefthandedge: Option<crate::LayoutDescriptorsBorderEdge> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LayoutDescriptorsBorderEdge::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let righthandedge: Option<crate::LayoutDescriptorsBorderEdge> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LayoutDescriptorsBorderEdge::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let trailingedge: Option<crate::LayoutDescriptorsBorderEdge> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LayoutDescriptorsBorderEdge::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let leadingedge: Option<crate::LayoutDescriptorsBorderEdge> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::LayoutDescriptorsBorderEdge::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                lefthandedge: lefthandedge,
                righthandedge: righthandedge,
                trailingedge: trailingedge,
                leadingedge: leadingedge,
            })

        })
    }
}

impl DERSerializable for LayoutDescriptorsBorder {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
