// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct ISOSTANDARD9541FONTATTRIBUTESETCPEAProperties {
    pub isostandard9541ncpeaforwd: crate::ISOSTANDARD9541FONTATTRIBUTESETCardinal,
    pub isostandard9541ncpeabackwd: crate::ISOSTANDARD9541FONTATTRIBUTESETCardinal,
    pub isostandard9541cpeax: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>,
    pub isostandard9541cpeay: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>,
    pub nonisoproperties: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList>,
}

impl ISOSTANDARD9541FONTATTRIBUTESETCPEAProperties {
    pub fn new(isostandard9541ncpeaforwd: crate::ISOSTANDARD9541FONTATTRIBUTESETCardinal, isostandard9541ncpeabackwd: crate::ISOSTANDARD9541FONTATTRIBUTESETCardinal, isostandard9541cpeax: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>, isostandard9541cpeay: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>, nonisoproperties: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList>) -> Self {
        Self {
            isostandard9541ncpeaforwd,
            isostandard9541ncpeabackwd,
            isostandard9541cpeax,
            isostandard9541cpeay,
            nonisoproperties,
        }
    }
}

impl DERParseable for ISOSTANDARD9541FONTATTRIBUTESETCPEAProperties {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let isostandard9541ncpeaforwd = crate::ISOSTANDARD9541FONTATTRIBUTESETCardinal::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let isostandard9541ncpeabackwd = crate::ISOSTANDARD9541FONTATTRIBUTESETCardinal::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let isostandard9541cpeax: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ISOSTANDARD9541FONTATTRIBUTESETRelRational::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let isostandard9541cpeay: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ISOSTANDARD9541FONTATTRIBUTESETRelRational::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let nonisoproperties: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                isostandard9541ncpeaforwd: isostandard9541ncpeaforwd,
                isostandard9541ncpeabackwd: isostandard9541ncpeabackwd,
                isostandard9541cpeax: isostandard9541cpeax,
                isostandard9541cpeay: isostandard9541cpeay,
                nonisoproperties: nonisoproperties,
            })

        })
    }
}

impl DERSerializable for ISOSTANDARD9541FONTATTRIBUTESETCPEAProperties {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
