// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct ISOSTANDARD9541FONTATTRIBUTESETPAdjustProperties {
    pub isostandard9541peax: Option<Vec<ASN1Node>>,
    pub isostandard9541peay: Option<Vec<ASN1Node>>,
    pub isostandard9541speaforwdx: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>,
    pub isostandard9541speaforwdy: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>,
    pub isostandard9541speabackwdx: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>,
    pub isostandard9541speabackwdy: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>,
    pub nonisoproperties: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList>,
}

impl ISOSTANDARD9541FONTATTRIBUTESETPAdjustProperties {
    pub fn new(isostandard9541peax: Option<Vec<ASN1Node>>, isostandard9541peay: Option<Vec<ASN1Node>>, isostandard9541speaforwdx: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>, isostandard9541speaforwdy: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>, isostandard9541speabackwdx: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>, isostandard9541speabackwdy: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>>, nonisoproperties: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList>) -> Self {
        Self {
            isostandard9541peax,
            isostandard9541peay,
            isostandard9541speaforwdx,
            isostandard9541speaforwdy,
            isostandard9541speabackwdx,
            isostandard9541speabackwdy,
            nonisoproperties,
        }
    }
}

impl DERParseable for ISOSTANDARD9541FONTATTRIBUTESETPAdjustProperties {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let isostandard9541peax: Option<Vec<ASN1Node>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); Some(collection.clone().into_iter().collect::<Vec<ASN1Node>>()) } else { None } } else { None };
            let isostandard9541peay: Option<Vec<ASN1Node>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); Some(collection.clone().into_iter().collect::<Vec<ASN1Node>>()) } else { None } } else { None };
            let isostandard9541speaforwdx: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ISOSTANDARD9541FONTATTRIBUTESETRelRational::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let isostandard9541speaforwdy: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ISOSTANDARD9541FONTATTRIBUTESETRelRational::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let isostandard9541speabackwdx: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ISOSTANDARD9541FONTATTRIBUTESETRelRational::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let isostandard9541speabackwdy: Option<Vec<ISOSTANDARD9541FONTATTRIBUTESETRelRational>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| ISOSTANDARD9541FONTATTRIBUTESETRelRational::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let nonisoproperties: Option<crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::ISOSTANDARD9541FONTATTRIBUTESETPropertyList::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                isostandard9541peax: isostandard9541peax,
                isostandard9541peay: isostandard9541peay,
                isostandard9541speaforwdx: isostandard9541speaforwdx,
                isostandard9541speaforwdy: isostandard9541speaforwdy,
                isostandard9541speabackwdx: isostandard9541speabackwdx,
                isostandard9541speabackwdy: isostandard9541speabackwdy,
                nonisoproperties: nonisoproperties,
            })

        })
    }
}

impl DERSerializable for ISOSTANDARD9541FONTATTRIBUTESETPAdjustProperties {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
