// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIXCMP2009PKIHeader {
    pub pvno: ASN1Integer,
    pub sender: PKIX1Implicit2009GeneralName,
    pub recipient: PKIX1Implicit2009GeneralName,
    pub message_time: Option<GeneralizedTime>,
    pub protection_alg: Option<algorithminformation2009::algorithm_information_2009::AlgorithmInformation2009AlgorithmIdentifier>,
    pub sender_kid: Option<PKIX1Implicit2009KeyIdentifier>,
    pub recip_kid: Option<PKIX1Implicit2009KeyIdentifier>,
    pub transaction_id: Option<ASN1OctetString>,
    pub sender_nonce: Option<ASN1OctetString>,
    pub recip_nonce: Option<ASN1OctetString>,
    pub free_text: Option<PKIXCMP2009PKIFreeText>,
    pub general_info: Option<Vec<PKIXCMP2009InfoTypeAndValue>>,
}

impl PKIXCMP2009PKIHeader {
    pub fn new(pvno: ASN1Integer, sender: PKIX1Implicit2009GeneralName, recipient: PKIX1Implicit2009GeneralName, message_time: Option<GeneralizedTime>, protection_alg: Option<algorithminformation2009::algorithm_information_2009::AlgorithmInformation2009AlgorithmIdentifier>, sender_kid: Option<PKIX1Implicit2009KeyIdentifier>, recip_kid: Option<PKIX1Implicit2009KeyIdentifier>, transaction_id: Option<ASN1OctetString>, sender_nonce: Option<ASN1OctetString>, recip_nonce: Option<ASN1OctetString>, free_text: Option<PKIXCMP2009PKIFreeText>, general_info: Option<Vec<PKIXCMP2009InfoTypeAndValue>>) -> Self {
        Self {
            pvno,
            sender,
            recipient,
            message_time,
            protection_alg,
            sender_kid,
            recip_kid,
            transaction_id,
            sender_nonce,
            recip_nonce,
            free_text,
            general_info,
        }
    }
}

impl DERParseable for PKIXCMP2009PKIHeader {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let pvno = ASN1Integer::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let sender = PKIX1Implicit2009GeneralName::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let recipient = PKIX1Implicit2009GeneralName::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let message_time: Option<GeneralizedTime> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match GeneralizedTime::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let protection_alg: Option<algorithminformation2009::algorithm_information_2009::AlgorithmInformation2009AlgorithmIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match algorithminformation2009::algorithm_information_2009::AlgorithmInformation2009AlgorithmIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let sender_kid: Option<PKIX1Implicit2009KeyIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match PKIX1Implicit2009KeyIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let recip_kid: Option<PKIX1Implicit2009KeyIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match PKIX1Implicit2009KeyIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let transaction_id: Option<ASN1OctetString> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1OctetString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let sender_nonce: Option<ASN1OctetString> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1OctetString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let recip_nonce: Option<ASN1OctetString> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match ASN1OctetString::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let free_text: Option<PKIXCMP2009PKIFreeText> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match PKIXCMP2009PKIFreeText::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let general_info: Option<Vec<PKIXCMP2009InfoTypeAndValue>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| PKIXCMP2009InfoTypeAndValue::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            Ok(Self {
                pvno: pvno,
                sender: sender,
                recipient: recipient,
                message_time: message_time,
                protection_alg: protection_alg,
                sender_kid: sender_kid,
                recip_kid: recip_kid,
                transaction_id: transaction_id,
                sender_nonce: sender_nonce,
                recip_nonce: recip_nonce,
                free_text: free_text,
                general_info: general_info,
            })

        })
    }
}

impl DERSerializable for PKIXCMP2009PKIHeader {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
