// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIXCMP2009CertifiedKeyPair {
    pub cert_or_enc_cert: PKIXCMP2009CertOrEncCert,
    pub private_key: Option<PKIXCRMF2009EncryptedValue>,
    pub publication_info: Option<PKIXCRMF2009PKIPublicationInfo>,
}

impl PKIXCMP2009CertifiedKeyPair {
    pub fn new(cert_or_enc_cert: PKIXCMP2009CertOrEncCert, private_key: Option<PKIXCRMF2009EncryptedValue>, publication_info: Option<PKIXCRMF2009PKIPublicationInfo>) -> Self {
        Self {
            cert_or_enc_cert,
            private_key,
            publication_info,
        }
    }
}

impl DERParseable for PKIXCMP2009CertifiedKeyPair {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let cert_or_enc_cert = PKIXCMP2009CertOrEncCert::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let private_key: Option<PKIXCRMF2009EncryptedValue> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match PKIXCRMF2009EncryptedValue::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let publication_info: Option<PKIXCRMF2009PKIPublicationInfo> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match PKIXCRMF2009PKIPublicationInfo::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                cert_or_enc_cert: cert_or_enc_cert,
                private_key: private_key,
                publication_info: publication_info,
            })

        })
    }
}

impl DERSerializable for PKIXCMP2009CertifiedKeyPair {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
