// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct PKIXCMP2009PKIMessage {
    pub header: PKIXCMP2009PKIHeader,
    pub body: PKIXCMP2009PKIBody,
    pub protection: Option<PKIXCMP2009PKIProtection>,
    pub extra_certs: Option<Vec<PKIXCMP2009CMPCertificate>>,
}

impl PKIXCMP2009PKIMessage {
    pub fn new(header: PKIXCMP2009PKIHeader, body: PKIXCMP2009PKIBody, protection: Option<PKIXCMP2009PKIProtection>, extra_certs: Option<Vec<PKIXCMP2009CMPCertificate>>) -> Self {
        Self {
            header,
            body,
            protection,
            extra_certs,
        }
    }
}

impl DERParseable for PKIXCMP2009PKIMessage {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let header = PKIXCMP2009PKIHeader::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let body = PKIXCMP2009PKIBody::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let protection: Option<PKIXCMP2009PKIProtection> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match PKIXCMP2009PKIProtection::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let extra_certs: Option<Vec<PKIXCMP2009CMPCertificate>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| PKIXCMP2009CMPCertificate::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            Ok(Self {
                header: header,
                body: body,
                protection: protection,
                extra_certs: extra_certs,
            })

        })
    }
}

impl DERSerializable for PKIXCMP2009PKIMessage {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
