// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum DORDefinitionQoSLevel {
    Level1(ASN1Null),
    Level2(GeneralizedTime),
    Level3(crate::DORDefinitionQoSLevelLevel3Sequence),
}

impl DERParseable for DORDefinitionQoSLevel {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (67, TagClass::ContextSpecific) => Ok(Self::Level1(ASN1Null::from_der_node(node)?)),
            (68, TagClass::ContextSpecific) => Ok(Self::Level2(GeneralizedTime::from_der_node(node)?)),
            (70, TagClass::ContextSpecific) => Ok(Self::Level3(crate::DORDefinitionQoSLevelLevel3Sequence::from_der_node(node)?)),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for DORDefinitionQoSLevel {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

