// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct LDAPMatchingRuleAssertion {
    pub matching_rule: Option<LDAPMatchingRuleId>,
    pub type_: Option<LDAPAttributeDescription>,
    pub match_value: LDAPAssertionValue,
    pub dn_attributes: ASN1Boolean,
}

impl LDAPMatchingRuleAssertion {
    pub fn new(matching_rule: Option<LDAPMatchingRuleId>, type_: Option<LDAPAttributeDescription>, match_value: LDAPAssertionValue, dn_attributes: ASN1Boolean) -> Self {
        Self {
            matching_rule,
            type_,
            match_value,
            dn_attributes,
        }
    }
}

impl DERParseable for LDAPMatchingRuleAssertion {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let matching_rule: Option<LDAPMatchingRuleId> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match LDAPMatchingRuleId::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let type_: Option<LDAPAttributeDescription> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match LDAPAttributeDescription::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let match_value = LDAPAssertionValue::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let dn_attributes = ASN1Boolean::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                matching_rule: matching_rule,
                type_: type_,
                match_value: match_value,
                dn_attributes: dn_attributes,
            })

        })
    }
}

impl DERSerializable for LDAPMatchingRuleAssertion {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
