// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct KEPBasicOCSPResponse {
    pub tbs_response_data: KEPResponseData,
    pub signature_algorithm: DSTUAlgorithmIdentifier,
    pub signature: ASN1BitString,
    pub certs: Option<Vec<DSTUCertificate>>,
}

impl KEPBasicOCSPResponse {
    pub fn new(tbs_response_data: KEPResponseData, signature_algorithm: DSTUAlgorithmIdentifier, signature: ASN1BitString, certs: Option<Vec<DSTUCertificate>>) -> Self {
        Self {
            tbs_response_data,
            signature_algorithm,
            signature,
            certs,
        }
    }
}

impl DERParseable for KEPBasicOCSPResponse {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let tbs_response_data = KEPResponseData::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let signature_algorithm = DSTUAlgorithmIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let signature = ASN1BitString::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let certs: Option<Vec<DSTUCertificate>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| DSTUCertificate::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            Ok(Self {
                tbs_response_data: tbs_response_data,
                signature_algorithm: signature_algorithm,
                signature: signature,
                certs: certs,
            })

        })
    }
}

impl DERSerializable for KEPBasicOCSPResponse {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
