// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct KEPRevocationValues {
    pub crl_vals: Option<Vec<KEPCertificateList>>,
    pub ocsp_vals: Option<Vec<KEPBasicOCSPResponse>>,
    pub other_rev_vals: Option<KEPOtherRevVals>,
}

impl KEPRevocationValues {
    pub fn new(crl_vals: Option<Vec<KEPCertificateList>>, ocsp_vals: Option<Vec<KEPBasicOCSPResponse>>, other_rev_vals: Option<KEPOtherRevVals>) -> Self {
        Self {
            crl_vals,
            ocsp_vals,
            other_rev_vals,
        }
    }
}

impl DERParseable for KEPRevocationValues {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let crl_vals: Option<Vec<KEPCertificateList>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| KEPCertificateList::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let ocsp_vals: Option<Vec<KEPBasicOCSPResponse>> = if let Some(node) = nodes.peek().map(|n| n.clone()) { if let rust_asn1::asn1::Content::Constructed(collection) = &node.content { nodes.next(); match collection.clone().into_iter().map(|child| KEPBasicOCSPResponse::from_der_node(child)).collect::<Result<_, _>>() { Ok(v) => Some(v), Err(_) => None } } else { None } } else { None };
            let other_rev_vals: Option<KEPOtherRevVals> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match KEPOtherRevVals::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                crl_vals: crl_vals,
                ocsp_vals: ocsp_vals,
                other_rev_vals: other_rev_vals,
            })

        })
    }
}

impl DERSerializable for KEPRevocationValues {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
