// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

use super::*;
use std::ops::Deref;

#[derive(Debug, Clone)]
pub struct ExtendedSecurityServices2009SecurityCategories(pub Vec<PKIXCommonTypes2009SecurityCategory>);

impl Deref for ExtendedSecurityServices2009SecurityCategories {
    type Target = Vec<PKIXCommonTypes2009SecurityCategory>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl DERParseable for ExtendedSecurityServices2009SecurityCategories {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
         // If inner type is ASN1Node, we collect manually
         let vec = rust_asn1::der::sequence_of(rust_asn1::asn1_types::ASN1Identifier::SEQUENCE, node)?; Ok(Self(vec))
    }
}

impl DERSerializable for ExtendedSecurityServices2009SecurityCategories {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
