// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct ExtendedSecurityServices2009ESSCertIDv2 {
    pub hash_algorithm: crate::ExtendedSecurityServices2009HashAlgorithm,
    pub cert_hash: crate::ExtendedSecurityServices2009Hash,
    pub issuer_serial: Option<crate::ExtendedSecurityServices2009IssuerSerial>,
}

impl ExtendedSecurityServices2009ESSCertIDv2 {
    pub fn new(hash_algorithm: crate::ExtendedSecurityServices2009HashAlgorithm, cert_hash: crate::ExtendedSecurityServices2009Hash, issuer_serial: Option<crate::ExtendedSecurityServices2009IssuerSerial>) -> Self {
        Self {
            hash_algorithm,
            cert_hash,
            issuer_serial,
        }
    }
}

impl DERParseable for ExtendedSecurityServices2009ESSCertIDv2 {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let hash_algorithm = crate::ExtendedSecurityServices2009HashAlgorithm::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let cert_hash = crate::ExtendedSecurityServices2009Hash::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let issuer_serial: Option<crate::ExtendedSecurityServices2009IssuerSerial> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::ExtendedSecurityServices2009IssuerSerial::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                hash_algorithm: hash_algorithm,
                cert_hash: cert_hash,
                issuer_serial: issuer_serial,
            })

        })
    }
}

impl DERSerializable for ExtendedSecurityServices2009ESSCertIDv2 {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
