// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct AuthenticationFrameworkCertificates {
    pub user_certificate: AuthenticationFrameworkCertificate,
    pub certification_path: Option<AuthenticationFrameworkForwardCertificationPath>,
}

impl AuthenticationFrameworkCertificates {
    pub fn new(user_certificate: AuthenticationFrameworkCertificate, certification_path: Option<AuthenticationFrameworkForwardCertificationPath>) -> Self {
        Self {
            user_certificate,
            certification_path,
        }
    }
}

impl DERParseable for AuthenticationFrameworkCertificates {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let user_certificate = AuthenticationFrameworkCertificate::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let certification_path: Option<AuthenticationFrameworkForwardCertificationPath> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match AuthenticationFrameworkForwardCertificationPath::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                user_certificate: user_certificate,
                certification_path: certification_path,
            })

        })
    }
}

impl DERSerializable for AuthenticationFrameworkCertificates {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
