// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct AuthenticationFrameworkAttributeCertificateInfo {
    pub version: AuthenticationFrameworkVersion,
    pub subject: AuthenticationFrameworkAttributeCertificateInfoSubjectChoice,
    pub issuer: PKIX1Implicit2009GeneralNames,
    pub signature: AuthenticationFrameworkAlgorithmIdentifier,
    pub serial_number: AuthenticationFrameworkCertificateSerialNumber,
    pub att_cert_validity_period: AuthenticationFrameworkAttCertValidityPeriod,
    pub attributes: Vec<PKIX1Explicit88Attribute>,
    pub issuer_unique_id: Option<SelectedAttributeTypesUniqueIdentifier>,
    pub extensions: Option<AuthenticationFrameworkExtensions>,
}

impl AuthenticationFrameworkAttributeCertificateInfo {
    pub fn new(version: AuthenticationFrameworkVersion, subject: AuthenticationFrameworkAttributeCertificateInfoSubjectChoice, issuer: PKIX1Implicit2009GeneralNames, signature: AuthenticationFrameworkAlgorithmIdentifier, serial_number: AuthenticationFrameworkCertificateSerialNumber, att_cert_validity_period: AuthenticationFrameworkAttCertValidityPeriod, attributes: Vec<PKIX1Explicit88Attribute>, issuer_unique_id: Option<SelectedAttributeTypesUniqueIdentifier>, extensions: Option<AuthenticationFrameworkExtensions>) -> Self {
        Self {
            version,
            subject,
            issuer,
            signature,
            serial_number,
            att_cert_validity_period,
            attributes,
            issuer_unique_id,
            extensions,
        }
    }
}

impl DERParseable for AuthenticationFrameworkAttributeCertificateInfo {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let version = AuthenticationFrameworkVersion::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let subject = AuthenticationFrameworkAttributeCertificateInfoSubjectChoice::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let issuer = PKIX1Implicit2009GeneralNames::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let signature = AuthenticationFrameworkAlgorithmIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let serial_number = AuthenticationFrameworkCertificateSerialNumber::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let att_cert_validity_period = AuthenticationFrameworkAttCertValidityPeriod::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let attributes: Vec<PKIX1Explicit88Attribute> = { let node = nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?; if let rust_asn1::asn1::Content::Constructed(collection) = node.content { collection.clone().into_iter().map(|child| PKIX1Explicit88Attribute::from_der_node(child)).collect::<Result<_, _>>()? } else { return Err(ASN1Error::new(rust_asn1::errors::ErrorCode::UnexpectedFieldType, "Expected constructed".to_string(), file!().to_string(), line!())); } };
            let issuer_unique_id: Option<SelectedAttributeTypesUniqueIdentifier> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match SelectedAttributeTypesUniqueIdentifier::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let extensions: Option<AuthenticationFrameworkExtensions> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match AuthenticationFrameworkExtensions::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                version: version,
                subject: subject,
                issuer: issuer,
                signature: signature,
                serial_number: serial_number,
                att_cert_validity_period: att_cert_validity_period,
                attributes: attributes,
                issuer_unique_id: issuer_unique_id,
                extensions: extensions,
            })

        })
    }
}

impl DERSerializable for AuthenticationFrameworkAttributeCertificateInfo {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
