// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct DefaultValueListsLogical {
    pub compositelogicalattributes: Option<crate::DefaultValueListsCompositeLogicalAttributes>,
    pub basiclogicalattributes: Option<crate::DefaultValueListsBasicLogicalAttributes>,
}

impl DefaultValueListsLogical {
    pub fn new(compositelogicalattributes: Option<crate::DefaultValueListsCompositeLogicalAttributes>, basiclogicalattributes: Option<crate::DefaultValueListsBasicLogicalAttributes>) -> Self {
        Self {
            compositelogicalattributes,
            basiclogicalattributes,
        }
    }
}

impl DERParseable for DefaultValueListsLogical {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let compositelogicalattributes: Option<crate::DefaultValueListsCompositeLogicalAttributes> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DefaultValueListsCompositeLogicalAttributes::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let basiclogicalattributes: Option<crate::DefaultValueListsBasicLogicalAttributes> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::DefaultValueListsBasicLogicalAttributes::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                compositelogicalattributes: compositelogicalattributes,
                basiclogicalattributes: basiclogicalattributes,
            })

        })
    }
}

impl DERSerializable for DefaultValueListsLogical {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
