// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct CryptographicMessageSyntax2009KEKRecipientInfo {
    pub version: crate::CryptographicMessageSyntax2009CMSVersion,
    pub kekid: crate::CryptographicMessageSyntax2009KEKIdentifier,
    pub key_encryption_algorithm: crate::CryptographicMessageSyntax2009KeyEncryptionAlgorithmIdentifier,
    pub encrypted_key: crate::CryptographicMessageSyntax2009EncryptedKey,
}

impl CryptographicMessageSyntax2009KEKRecipientInfo {
    pub fn new(version: crate::CryptographicMessageSyntax2009CMSVersion, kekid: crate::CryptographicMessageSyntax2009KEKIdentifier, key_encryption_algorithm: crate::CryptographicMessageSyntax2009KeyEncryptionAlgorithmIdentifier, encrypted_key: crate::CryptographicMessageSyntax2009EncryptedKey) -> Self {
        Self {
            version,
            kekid,
            key_encryption_algorithm,
            encrypted_key,
        }
    }
}

impl DERParseable for CryptographicMessageSyntax2009KEKRecipientInfo {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let version = crate::CryptographicMessageSyntax2009CMSVersion::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let kekid = crate::CryptographicMessageSyntax2009KEKIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let key_encryption_algorithm = crate::CryptographicMessageSyntax2009KeyEncryptionAlgorithmIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let encrypted_key = crate::CryptographicMessageSyntax2009EncryptedKey::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            Ok(Self {
                version: version,
                kekid: kekid,
                key_encryption_algorithm: key_encryption_algorithm,
                encrypted_key: encrypted_key,
            })

        })
    }
}

impl DERSerializable for CryptographicMessageSyntax2009KEKRecipientInfo {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
