// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct CryptographicMessageSyntax2009SignerInfo {
    pub version: crate::CryptographicMessageSyntax2009CMSVersion,
    pub sid: crate::CryptographicMessageSyntax2009SignerIdentifier,
    pub digest_algorithm: crate::CryptographicMessageSyntax2009DigestAlgorithmIdentifier,
    pub signed_attrs: Option<crate::CryptographicMessageSyntax2009SignedAttributes>,
    pub signature_algorithm: crate::CryptographicMessageSyntax2009SignatureAlgorithmIdentifier,
    pub signature: crate::CryptographicMessageSyntax2009SignatureValue,
    pub unsigned_attrs: Option<crate::CryptographicMessageSyntax2009Attributes>,
}

impl CryptographicMessageSyntax2009SignerInfo {
    pub fn new(version: crate::CryptographicMessageSyntax2009CMSVersion, sid: crate::CryptographicMessageSyntax2009SignerIdentifier, digest_algorithm: crate::CryptographicMessageSyntax2009DigestAlgorithmIdentifier, signed_attrs: Option<crate::CryptographicMessageSyntax2009SignedAttributes>, signature_algorithm: crate::CryptographicMessageSyntax2009SignatureAlgorithmIdentifier, signature: crate::CryptographicMessageSyntax2009SignatureValue, unsigned_attrs: Option<crate::CryptographicMessageSyntax2009Attributes>) -> Self {
        Self {
            version,
            sid,
            digest_algorithm,
            signed_attrs,
            signature_algorithm,
            signature,
            unsigned_attrs,
        }
    }
}

impl DERParseable for CryptographicMessageSyntax2009SignerInfo {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let version = crate::CryptographicMessageSyntax2009CMSVersion::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let sid = crate::CryptographicMessageSyntax2009SignerIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let digest_algorithm = crate::CryptographicMessageSyntax2009DigestAlgorithmIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let signed_attrs: Option<crate::CryptographicMessageSyntax2009SignedAttributes> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::CryptographicMessageSyntax2009SignedAttributes::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let signature_algorithm = crate::CryptographicMessageSyntax2009SignatureAlgorithmIdentifier::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let signature = crate::CryptographicMessageSyntax2009SignatureValue::from_der_node(nodes.next().ok_or(ASN1Error::new(rust_asn1::errors::ErrorCode::TruncatedASN1Field, "Premature end of data".to_string(), file!().to_string(), line!()))?)?;
            let unsigned_attrs: Option<crate::CryptographicMessageSyntax2009Attributes> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::CryptographicMessageSyntax2009Attributes::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                version: version,
                sid: sid,
                digest_algorithm: digest_algorithm,
                signed_attrs: signed_attrs,
                signature_algorithm: signature_algorithm,
                signature: signature,
                unsigned_attrs: unsigned_attrs,
            })

        })
    }
}

impl DERSerializable for CryptographicMessageSyntax2009SignerInfo {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
