// Generated by ASN1.ERP.UNO Compiler -- Rust emitter
use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub enum CryptographicMessageSyntax2009CertificateChoices {
    Certificate(crate::PKIX1Explicit2009Certificate),
    ExtendedCertificate(crate::CryptographicMessageSyntax2009ExtendedCertificate),

    V1AttrCert(ASN1Node),
    V2AttrCert(crate::CryptographicMessageSyntax2009AttributeCertificateV2),
    Other(crate::CryptographicMessageSyntax2009OtherCertificateFormat),
}

impl DERParseable for CryptographicMessageSyntax2009CertificateChoices {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        match (node.identifier.tag_number, node.identifier.tag_class) {
            (316, TagClass::ContextSpecific) => Ok(Self::Certificate(crate::PKIX1Explicit2009Certificate::from_der_node(node)?)),
            (317, TagClass::ContextSpecific) => Ok(Self::ExtendedCertificate(crate::CryptographicMessageSyntax2009ExtendedCertificate::from_der_node(node)?)),
            (320, TagClass::ContextSpecific) => Ok(Self::V1AttrCert(node)),
            (322, TagClass::ContextSpecific) => Ok(Self::V2AttrCert(crate::CryptographicMessageSyntax2009AttributeCertificateV2::from_der_node(node)?)),
            (323, TagClass::ContextSpecific) => Ok(Self::Other(crate::CryptographicMessageSyntax2009OtherCertificateFormat::from_der_node(node)?)),
            _ => Err(ASN1Error::new(
                rust_asn1::errors::ErrorCode::UnexpectedFieldType,
                format!("{}", node.identifier),
                file!().to_string(),
                line!(),
            )),
        }
    }
}

impl DERSerializable for CryptographicMessageSyntax2009CertificateChoices {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}

