// Generated by ASN1.ERP.UNO Compiler -- Rust emitter

use std::sync::Arc;
use rust_asn1::{
    asn1::ASN1Node,
    asn1_types::*,
    der::{self, DERParseable, DERSerializable, Serializer},
    errors::ASN1Error,
};
use super::*;

#[derive(Clone, Debug)]
pub struct StyleDescriptorsFloatabilityRange {
    pub forwardlimit: Option<crate::StyleDescriptorsFloatabilityRangeForwardLimitSequence>,
    pub backwardlimit: Option<crate::StyleDescriptorsFloatabilityRangeBackwardLimitSequence>,
}

impl StyleDescriptorsFloatabilityRange {
    pub fn new(forwardlimit: Option<crate::StyleDescriptorsFloatabilityRangeForwardLimitSequence>, backwardlimit: Option<crate::StyleDescriptorsFloatabilityRangeBackwardLimitSequence>) -> Self {
        Self {
            forwardlimit,
            backwardlimit,
        }
    }
}

impl DERParseable for StyleDescriptorsFloatabilityRange {
    fn from_der_node(node: ASN1Node) -> Result<Self, ASN1Error> {
        der::sequence(node, ASN1Identifier::SEQUENCE, |nodes| {
            let all_nodes: Vec<ASN1Node> = nodes.collect();
            let mut iter = all_nodes.into_iter().peekable();
            let nodes = &mut iter;
            let forwardlimit: Option<crate::StyleDescriptorsFloatabilityRangeForwardLimitSequence> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::StyleDescriptorsFloatabilityRangeForwardLimitSequence::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            let backwardlimit: Option<crate::StyleDescriptorsFloatabilityRangeBackwardLimitSequence> = if let Some(node) = nodes.peek().map(|n| n.clone()) { match crate::StyleDescriptorsFloatabilityRangeBackwardLimitSequence::from_der_node(node.clone()) { Ok(val) => { nodes.next(); Some(val) }, Err(_) => None } } else { None };
            Ok(Self {
                forwardlimit: forwardlimit,
                backwardlimit: backwardlimit,
            })

        })
    }
}

impl DERSerializable for StyleDescriptorsFloatabilityRange {
    fn serialize(&self, _serializer: &mut Serializer) -> Result<(), ASN1Error> {
        Err(ASN1Error::new(
            rust_asn1::errors::ErrorCode::UnsupportedFieldLength,
            "Serialization is not implemented by the generator yet.".to_string(),
            file!().to_string(),
            line!(),
        ))
    }
}
